### ISSUE TITLE
Epic: Incorporate Jetpack DNA Connection package

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#111]
These are all the sub-tasks, as listed in paJDYF-tU-p2

### Library tasks
- [ ] Use the blog token for authentication for “make-payment-type” requests to decrease connection error problems. Still use the user token for more "sensitive" requests, such as updating personal or financial data.
- [ ] Ensure that older versions of Jetpack will work with the library.
- [ ] Ensure that users do not unknowingly disconnect WC Pay when they disconnect Jetpack.
- [ ] Ensure setting a redirect_url in wp-admin works for us, so the user doesn't get dropped into a (non-existant) Jetpack dashboard screen after completing the connection flow.
- [ ] What does it mean for us when the master user changes?
- [ ] Ensure we can use passwordless flow.

### Connection flow (initial design post: paJDYF-dX-p2, design i2: paJDYF-eJ-p2)
- [ ] Implement the “not currently connected” flow.
- [ ] Implement the “already connected” flow.
- [ ] Spike on what happens when a store is set up as a test / local site first. And then changed to a live site.
- [ ] Investigate what happens when there’s a staging site.
- [ ] Do we want to handle the store builder flow, where the user that connects Jetpack/WCPay isn't the merchant?
- [ ] How do we handle Jetpack identity crises?

### Error handling (paJDYF-tL-p2)
- [ ] Are there any implications for using blog tokens instead of user tokens for making checkout requests? For example, any TOS issues.
- [ ] Look into the recommendation to “[not] purge sites that we can’t talk to unless those sites are also not talking to us”
- [ ] Can we find a percentage of requests with errors to understand the risk better?

cc @zinigor @gravityrail  @marcinbot @v18 @DanReyLop @RadoslavGeorgiev
