### ISSUE TITLE
Epic: Add support for non SCA recurring transactions (subscriptions)

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#117]
Add initial support for WC Subscriptions by supporting transactions that do not require 3D Secure.

Requires:

- [x] Processing sign-ups https://github.com/Automattic/woocommerce-payments/issues/697
- [x] Handling subscriber initiated payment method changes https://github.com/Automattic/woocommerce-payments/issues/698
- [x] Integrating with My Account features https://github.com/Automattic/woocommerce-payments/issues/699
- [x] Support merchant initiated payment method changes https://github.com/Automattic/woocommerce-payments/issues/700

---

Update ( @dwainm ) Make sure we  send metadata with intent as per:
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.3.1/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L352-L365

Update ( @allendav) paJDYF-Hs-p2

Update ( @thenbrent ) added child issues as todos.

**Comment by DanReyLop** [comment]
We can consider this done. Only #700 is missing and it will be merged once Luiz wakes up :)
