### ISSUE TITLE
Register all WC Pay track events

### ISSUE THREAD

**Issue by ismaeldcom** [Automattic/woocommerce-payments#1521]
After a conversation about events in slack (p1617362163015600-slack-CGGCLBN58), this [PR](https://github.com/Automattic/woocommerce-payments/pull/1479) and some internal chats we agreed to register all WC Pay tracks events. Because as the FG (PCYsg-mUj-p2) states *“In the future, Tracks tools will only use registered events”*

## Tasks to complete

- [x] Add the new event `wcadmin_wcpay_transactions_download` to PCYsg-r6P-p2
- [x] Register event `wcadmin_wcpay_transactions_download` to clarify the parameters 474-gh-Automattic/tracks-events-registration

### Register the existing events:

- [x] wcadmin_wcpay_connect_account_clicked (https://github.com/Automattic/tracks-events-registration/pull/2536)
- [x] wcadmin_wcpay_edit_order_refund_failure (https://github.com/Automattic/tracks-events-registration/pull/2537)
- [x] wcadmin_wcpay_edit_order_refund_success (https://github.com/Automattic/tracks-events-registration/pull/2538)
- [x] wcadmin_wcpay_merchant_captured_auth (https://github.com/Automattic/tracks-events-registration/pull/2539)
- [x] wcadmin_wcpay_dispute_file_upload_started (https://github.com/Automattic/tracks-events-registration/pull/2540)
- [x] wcadmin_wcpay_dispute_file_upload_success (https://github.com/Automattic/tracks-events-registration/pull/2541)
- [x] wcadmin_wcpay_dispute_file_upload_failed (https://github.com/Automattic/tracks-events-registration/pull/2542)
- [x] wcadmin_wcpay_dispute_submit_evidence_success (https://github.com/Automattic/tracks-events-registration/pull/2543)
- [x] wcadmin_wcpay_dispute_submit_evidence_failed (https://github.com/Automattic/tracks-events-registration/pull/2544)
- [x] wcadmin_wcpay_dispute_submit_evidence_clicked (https://github.com/Automattic/tracks-events-registration/pull/2545)
- [x] wcadmin_wcpay_dispute_save_evidence_clicked (https://github.com/Automattic/tracks-events-registration/pull/2546)
- [x] wcadmin_wcpay_dispute_product_selected (https://github.com/Automattic/tracks-events-registration/pull/2547)
- [x] wcadmin_wcpay_dispute_accept_success (https://github.com/Automattic/tracks-events-registration/pull/2548)
- [x] wcadmin_wcpay_dispute_accept_click (Already registered)
- [x] wcadmin_wcpay_dispute_accept_failed (https://github.com/Automattic/tracks-events-registration/pull/2549)
- [x] wcadmin_wcpay_dispute_challenge_clicked (Already registered)
- [x] wcadmin_wcpay_view_submitted_evidence_clicked (Already registered)
- [x] wcadmin_wcpay_deposits_download (Already registered)
- [x] wcadmin_wcpay_multi_currency_enabled_currencies_updated (https://github.com/Automattic/tracks-events-registration/pull/2550)
- [x] wcadmin_wcpay_welcome_learn_more (https://github.com/Automattic/tracks-events-registration/pull/2552)
- [x] wcadmin_wcpay_stripe_connected (https://github.com/Automattic/tracks-events-registration/pull/2553)
- [x] wcadmin_wcpay_apple_pay_domain_registration_success (https://github.com/Automattic/tracks-events-registration/pull/2554)
- [x] wcadmin_wcpay_apple_pay_domain_registration_failure (https://github.com/Automattic/tracks-events-registration/pull/2555)
- [x] wcadmin_wcpay_payment_request_settings_change (https://github.com/Automattic/tracks-events-registration/pull/2556)
- [x] wcadmin_wcpay_upe_enabled (Already registered)
- [x] wcadmin_wcpay_upe_disabled
- [x] wcadmin_wcpay_disputes_download (https://github.com/Automattic/tracks-events-registration/pull/2558)
- [x] wcadmin_wcpay_split_upe_enabled (https://github.com/Automattic/tracks-events-registration/pull/2559)
- [x] wcadmin_wcpay_split_upe_disabled (https://github.com/Automattic/tracks-events-registration/pull/2560)

**Comment by a-danae** [comment]
@ismaeldcom I've included in the issue's list two tracks I added to WCPay and registered.

I see we have to update this list PCYsg-r6P-p2 to include them but looks like I'm missing that option. 

I also noticed there are some events that are neither registered nor in the list above:
* wcadmin_page_view (it's mentioned on the FG page, but isn't in the events list)
* wcpay_welcome_learn_more
* wcpay_stripe_connected
* wcpay_multi_currency_enabled_currencies_updated (is on the FG page but it's not registered)
* wcpay_apple_pay_domain_registration_success
* wcpay_apple_pay_domain_registration_failure
* wcpay_payment_request_settings_change

I'm not sure if we're omitting these for some reason, so letting you know instead of updating the issue description.

**Comment by ismaeldcom** [comment]
Thanks @a-danae for pointing this out!

Looks like we were missing some events on the P2 list, I updated it and this issue too, feel free to update both in the future if you need to 🙂 

I have left only `wcadmin_page_view` because it's not from WCPay, although we use it.

**Comment by a-danae** [comment]
My pleasure!

Ah, got it. Thanks for clarifying! 🙂

**Comment by mgascam** [comment]
Hi, I added a new track event `wcadmin_wcpay_disputes_download` that was implemented in [this PR](https://github.com/Automattic/woocommerce-payments/pull/3418). I also updated the list in PCYsg-r6P-p2.

Thanks!

**Comment by achyuthajoy** [comment]
Events registered and P2 published here - paJDYF-efT-p2
