### ISSUE TITLE
Epic: Connect Transactions List View Filters through to WPCOM transactions layer

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#156]
Change WC_Payments_API_Client to pass next priority queries through to WPCOM; wire up filtering controls in SPA through to WC_REST_Payments_Transactions_Controller

Depends on https://github.com/Automattic/woocommerce-payments-server/issues/36

paJDYF-dc-p2

- [x] Add fields sorting to transactions list #595 
- [x] Add v1 filters to transaction list #596
    - [x] Add transaction date and type filters to transaction list #615
    - [ ] Add customer name and email filters to transaction list #616
- [x] Add search bar to transaction list #597

**Comment by vbelolapotkov** [comment]
closing this one, since only #616 is left
