### ISSUE TITLE
Implement a collapsible Task List in the overview screen

### ISSUE THREAD

**Issue by samueljseay** [Automattic/woocommerce-payments#1656]
This is to implement the collapsible task list (For the designs see paJDYF-18j-p2) utilising new components from.`@woocommerce/components`.

The `ExperimentalList`, `ExperimentalListItem`  and TBD collapsible component developed in https://github.com/woocommerce/woocommerce-admin/issues/6772 and https://github.com/woocommerce/woocommerce-admin/issues/6636 will need to be completed / published before this can go ahead.

The header can be recreated to match the one in wc-admin, for now there is not an immediate plan to expose a component for that, but it could come later.

This task does not cover adding the task items, so we could look at putting it behind a feature flag till the task items are done.

cc @pmcpinto 

- [x] Release `@woocommerce/experimental` package
- [x] ~Add new (empty) overview screen behind a feature flag~ (https://github.com/Automattic/woocommerce-payments/pull/1368)
- [ ] Add empty task list to the overview screen

**Comment by louwie17** [comment]
A question from looking at https://github.com/woocommerce/woocommerce-admin/issues/6636 and the designs mentioned above.
In what instance would we collapse the entire list (as shown in the WC Pay designs), and when do we only collapse/hide the extra unfinished list items as shown in https://github.com/woocommerce/woocommerce-admin/issues/6636 ?
<img width="476" alt="Screen Shot 2021-04-22 at 10 25 53 AM" src="https://user-images.githubusercontent.com/2240960/115722222-29935080-a355-11eb-83e6-20c27fda7863.png">

cc: @elizaan36

**Comment by elizaan36** [comment]
For simplicity's sake would be best to match the list behavior in #6636 on the payments overview screen.
That would mean two tasks show by default with the option to expand the list. And if there are only one or two tasks, the footer doesn't appear. 

@LevinMedia could you share more about the reason you suggested to collapse the full list on the payments overview? Want to make sure I'm not missing anything.

**Comment by timmyc** [comment]
> The ExperimentalList, ExperimentalListItem and TBD collapsible component developed in woocommerce/woocommerce-admin#6772 and woocommerce/woocommerce-admin#6636 will need to be completed / published before this can go ahead.

I think there had been some conversation around the challenges here of the Overview page requiring a specific version of Woo Core / WC Admin in order to use the new components. Should we have an issue specifically around that?

I see a feature flag being mentioned, in the epic issue itself - and agree that is a great thing to have too, but we still need to have something in place to either _hide_ the overview page if Woo requirements are not satisfied, or maybe have a page encouraging the user to upgrade Woo to "unlock" the new feature. @elizaan36 curious for your thoughts on how to handle that from a UX standpoint too. But think we should work that issue/work into this epic too.

**Comment by elizaan36** [comment]
WC Admin could introduce an L3 task in the extended task list to update the version, "Update to have access to new features". Probably something to do regardless for version updates.

Yeah, I think best path forward beyond that is to show/hide the overview screen depending on whether the Woo requirements are being met.

Not sure about introducing a new page or other global element specifically related to the new feature, that seems like a lot.😆

**Comment by samueljseay** [comment]
@timmyc we intended to get around the version requirements by bundling these new components in wc pay so there is no wc admin dependency.

**Comment by jeffstieler** [comment]
I think refactoring to create reusable components for the overview page is the way to go, lest we duplicate quite a lot of code that powers the "task list in a dashboard" functionality.

I've started to capture the work in this issue: https://github.com/woocommerce/woocommerce-admin/issues/6944

**Comment by jeffstieler** [comment]
> I think refactoring to create reusable components for the overview page is the way to go

Just noting here that we've chosen to duplicate some code now in an effort to hopefully avoid repeating some less desirable patterns in the existing implementation.

Estimate: 2

**Comment by louwie17** [comment]
@jeffstieler I believe this would just require a npm release of `woocommerce/experimental`

**Comment by LevinMedia** [comment]
>@LevinMedia could you share more about the reason you suggested to collapse the full list on the payments overview? Want to make sure I'm not missing anything.

Hey @elizaan36 sorry I missed this ping - I actually intended for the opposite to be true. On the payments overview screen, the task list would be expanded to show all payments related tasks by default, rather than hidden. 

ITsL0PJ0Xz4ZzQpsWyMgiI-fi-1646%3A7665
