### ISSUE TITLE
Implement WCPay Empty States Preview Mode experiment

### ISSUE THREAD

**Issue by mattsherman** [Automattic/woocommerce-payments#1815]
*Note: This is a part of the larger Preview Mode project (paJDYF-1rg-p2).*

## User story

As a merchant who has installed WCPay but not completed the KYC, I want to see the Deposits and Transactions menu items so that I can click on them and find out more about how to finish setting up WCPay.

## Acceptance criteria

- An [ExPlat](https://github.com/Automattic/experimentation-platform/wiki) experiment named `wcpay_empty_state_preview_mode` is used to assign merchants with Tracks enabled to one of two experiences:
	- `control`: The default experience; only the Payments top level menu item is available when the WCPay plugin is activated and the KYC is not completed
	- `empty_states`: the experience we are testing; the Deposits and Transactions menu items are shown when the WCPay plugin is activated and the KYC is not completed; selecting those menu items shows an empty state variation of those screens  

## Tasks

- [x] Experiment design work (see [Experiment Checklist])
    - What is our hypothesis?
    - Primary metric: `wcadmin_wcpay_connect_account_button_clicked`
    - Secondary metric: `wcadmin_wcpay_stripe_connected ` (this is a new metric that we will have to have created)
- [x] Create experiment in [Abacus](https://experiments.a8c.com/experiments)
- [x] Implement support for [ExPlat](https://github.com/Automattic/experimentation-platform/wiki) experiment assignments from PHP, similar to [@woocommerce/explat](https://github.com/woocommerce/woocommerce-admin/tree/main/packages/explat)
	- This should be right in WooCommerce Core, so that anybody can use it
	- Will need to implement this in PHP
- [x] Implement experiment assignment when determining whether to show the Desposits and Transactions menu item ([code where admin menu items are added]( https://github.com/Automattic/woocommerce-payments/blob/0bec587e29b907df3b67cbf7c027d93ceb39bc0c/includes/admin/class-wc-payments-admin.php))
    - We will need to have the ExPlat team review this work in order for the experiment to be launchable
- [x] Show empty Deposits screen skeleton `empty_states` experience is assigned
	- use [@woocommerce/explat](https://github.com/woocommerce/woocommerce-admin/tree/main/packages/explat)
	- Full empty state experience for Deposits screen will be implemented in follow-up story
- [x] Show empty Transactions screen skeleton when `empty_states` experience is assigned
	- use [@woocommerce/explat](https://github.com/woocommerce/woocommerce-admin/tree/main/packages/explat)
	- Full empty state experience for Transactions screen will be implemented in follow-up story

**Comment by pmcpinto** [comment]
> What primary metric are we using?
> wcadmin_wcpay_connect_account_button_clicked isn't quite what we want; we want to to know if the user has completed the KYC

My suggestion is to use `wcadmin_wcpay_connect_account_button_clicked` (proceeding to the kyc) as the primary metric and wcadmin_wcpay_stripe_connected (completing to the kyc) as the secondary metric.

**Comment by adrianduffell** [comment]
@oneillo Will you work on the initial experiment design for this?

**Comment by oneillo** [comment]
> Will you work on the initial experiment design for this?

@adrianduffell - will do. I'm catching up after a holiday, but I'm aiming to get to it this week.

**Comment by moon0326** [comment]
Hey @oneillo ✋ Are there any updates on the experiment? I would like to start testing it soon. Thank you!

**Comment by oneillo** [comment]
@moon0326 - the experiment design passed internal review. I'll get it set up in the system today and let you know when it's good to go. It will likely need to run for at least 3 weeks.

**Comment by adrianduffell** [comment]
This was implemented in #1963 and #2253
