### ISSUE TITLE
Single task for all open disputes

### ISSUE THREAD

**Issue by mattsherman** [Automattic/woocommerce-payments#2712]
This issue supersedes #1658.

### User story

As a merchant, I want to be reminded that I have open disputes that require my attention, so that I can respond to them in a timely manner.

### Notes

We will show a single task for all disputes. When there are open disputes, the task will be marked uncompleted. When there are only completed disputes, the task will be marked completed.

#### Open disputes

![126514220-4e70ba3f-4485-4b36-8c92-e3db281f233c.png](https://images.zenhubusercontent.com/5e78cac2867c853084b981b0/94de72de-f863-4924-ada0-b81120ecaeb3)

#### All disputes completed

![127218298-833fda80-8bde-4b0f-8ed9-7680a2870e49.png](https://images.zenhubusercontent.com/5e78cac2867c853084b981b0/087cd8a8-0985-49a1-98be-21a3535c3742)

### Acceptance criteria

- [ ] When there are open disputes, a single task will be shown with the total number of open disputes
- [ ] When there are only closed disputes, a single completed task will be shown with the total number of closed disputes
- [ ] When there are no disputes at all in the system, no task will be shown
- [ ] Clicking on the task will open the disputes overview screen
- [ ] A Tracks event will be logged when the task is clicked on

### Tasks

See PR #2148 for the initial implementation of the dispute task (a single task per dispute) -- we should be able to either continue with that PR or use it as inspiration. Much of the work will stay the same.

- [ ] Implement dispute task
    - Either pre-load data (try to avoid this), or
    - Use API (felt slow in #2148)
- [ ] Add e2e tests to cover this
- [ ] Add [release testing instructions for WC Payments 2.9.0](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions-for-WC-Payments-2.9.0)

**Comment by mattsherman** [comment]
@elizaan36 @pmcpinto @LevinMedia What should happen when all disputes are completed and then another dispute is opened? Do we show the completed task and a new task?

**Comment by elizaan36** [comment]
Yea I imagine that the task will catch all open disputes until completed, so the count can increase while the task is open? @LevinMedia to confirm.

Once this task is completed, a new dispute would have to trigger a new task. This would appear alongside the previous completed disputes task.

**Comment by LevinMedia** [comment]
@elizaan36 that sounds good to me, thanks 👍

**Comment by mattsherman** [comment]
@joelclimbsthings @louwie17 You two are the outliers for estimates. Any particulars aspects that caused you to vote the way you did? (I normally would have this conversation on a call, but figured we could try it async right in the issue!)

**Comment by louwie17** [comment]
> @joelclimbsthings @louwie17 You two are the outliers for estimates. Any particulars aspects that caused you to vote the way you did? (I normally would have this conversation on a call, but figured we could try it async right in the issue!)

I could waiver to a 3, the only thing I wasn't sure about how long it would take was fixing the slowness of the dispute API, but I thought that could be solved within a day. The rest of the work should only take half a day or less given Fernando has done the bulk of the work.
Given the unknown of the disputes api a `3` is fine with me.

**Comment by joelclimbsthings** [comment]
I was torn between 3 & 5, so I'm good with 3. I'd actually forgotten that part of this work was already done in https://github.com/Automattic/woocommerce-payments/pull/2148, and given that fact a three is definitely more appropriate (although 3 days is a full week for me 😝 )

**Comment by mattsherman** [comment]
Thanks, @louwie17 and @joelclimbsthings! Since we are just getting started with estimating and all the estimates were pretty close, I'll just go with a 3 instead of having the whole team re-vote.

**Comment by octaedro** [comment]
Hi @pmcpinto, @elizaan36,
I'm working on this issue now. I will add a tracking event for this task. 
If it's ok for you I'm going to use the event name: `wcpay_overview_task` with type: `dispute-resolution-task` every time the task item is clicked.
