### ISSUE TITLE
Red badge: display it 3 days after the plugin activation

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/woocommerce-payments#2837]
**Description:** showing the red badge 7 days after the plugin activation is not having the impact that we were expecting (#2071). See the results here: p1626887687077600-slack-wcpay-growth
We're still trying to find a good balance between taking advantage of the red badge effectiveness to increase the focus on WCPayments without distracting users or hurting the WCPayments activation.

**Acceptance criteria:**

- [ ] Start showing the red badge 3 days after the plugin activation if the user still needs to complete the WCPayments setup. Don't show it if the user already created a WCPayments account. 

**Tasks:**

- [ ] Change check from 7 days to 3 days in `WC_Payments_Admin::add_menu_notification_badge()` ([source](https://github.com/Automattic/woocommerce-payments/blob/fba91fd6d66fefdc6d1ddd67a00714ea6b2215a2/includes/admin/class-wc-payments-admin.php#L598))
- [ ] Change associated unit tests

**Comment by pmcpinto** [comment]
@joshuatf I just saw that this has been under review since last month. Is there something missing to merge the PR and release this change?

**Comment by joshuatf** [comment]
Hey @pmcpinto, sorry about the delay.  That PR just got approved yesterday so I'll be merging today and it will be available in the next WC Pay release.

**Comment by pmcpinto** [comment]
👍 thanks for the update!
