### ISSUE TITLE
WCPay Subscriptions phase 4: Downgrade flows

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#2868]
An epic for tracking upgrade/downgrade related issues for migrating between WC Subscriptions and WCPay Subscriptions.

Sub-project: pdjTHR-35-p2

### Key User Flows

- [x] https://github.com/Automattic/woocommerce-payments/issues/2960 - **MVP**  
- [x] https://github.com/Automattic/woocommerce-payments/issues/2961 - **MVP** 

### Infrastructure

- [x] 🟢 https://github.com/Automattic/woocommerce-payments/issues/2963 - **MVP**

### Downgrading
- [x]  https://github.com/Automattic/woocommerce-payments/pull/2909
- [x] 🟢 https://github.com/Automattic/woocommerce-subscriptions-core/issues/1.

**Comment by haszari** [comment]
Looks like all the linked issues are resolved so I'm going to close this.

@james-allan is there any additional work or follow up here that we should prioritise? If so let me know and we can add issues.
