### ISSUE TITLE
WCPay Subscriptions: Upgrading and Downgrading flows

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#3103]
An epic for tracking upgrade/downgrade related issues for migrating between WC Subscriptions and WCPay Subscriptions.

Sub-project: pdjTHR-35-p2

**Key User Flows**

- [ ]  #2962

**Background script infrastructure**
- [x] #2894
- [ ]  #2908
- [ ] Add migration tracking information so merchants know how far along their migrations are.

**Upgrading**

- [x] #2880
- [x] #2981

**Downgrading**

- [ ] Add information to the edit subscription and admin list table to indicate if a subscription has been set to manual and is pending set up with Stripe billing.
- [x] #2896
- [x] #2897
- [ ] Send email to customers when their subscription is set to manual with instructions and a link on how to set up their subscription with WCPay via Stripe Billing.
- [ ] Store meta on the subscription to track subscriptions that have been turned into manual subscriptions - for tracking purposes.

**Comment by haszari** [comment]
@james-allan let's get this epic issue closed. Of the tasks & issues listed in the description, are any are still relevant for possible inclusion in future releases?

**Comment by james-allan** [comment]
Following our discussion, I've closed off all the issues related to this epic. If we revisit upgrade and downgrade flows in a future release we can reopen or recreate them given the new context we're working from.
