### ISSUE TITLE
Epic: Deposits list view

### ISSUE THREAD

**Issue by luizreis** [Automattic/woocommerce-payments#351]
paJDYF-6G-p2

- [x] Server endpoints https://github.com/Automattic/woocommerce-payments-server/issues/11
- [x] Table with list of deposits https://github.com/Automattic/woocommerce-payments/issues/365
- [x] Overview component https://github.com/Automattic/woocommerce-payments/issues/366
