### ISSUE TITLE
Add Jetpack identity-crisis package to handle IDC

### ISSUE THREAD

**Issue by htdat** [Automattic/woocommerce-payments#3566]
### Description

p9dueE-3Mn-p2#comment-6943
p9dueE-46U-p2

As mentioned p1640144584013800/1639517545.011100-slack-CPBTESZMG, we're targeting to add this feature for WCPay 3.6.0.

### Acceptance criteria

* Add this package to composer https://github.com/Automattic/jetpack-identity-crisis
* Texts in IDC banners should not be confusing in case Jetpack is not active.
* Prepare manual test steps for GlobalStep.

### Todos 

- [x] Add `customContent` for WCPay (texts, logos, etc).
- [x] Currently all Woo settings pages (wp-admin/admin.php?page=wc-settings) including WCPay settings page do not display the IDC banner. I am trying to suggest a fix here https://github.com/Automattic/jetpack/pull/22266
- [x] Enhancement from Jetpack: Allow `strong` and `em` tags in customized texts p9dueE-3Xf-p2#comment-7006 https://github.com/Automattic/jetpack/pull/22360
- [x] Enhancement from Jetpack: Customize texts for two buttons `Move your settings` & `Create a fresh connection too` https://github.com/Automattic/jetpack/pull/22394?
- [x] Enhancement from Jetpack: Customize support link to explain Safe Mode https://github.com/Automattic/jetpack/pull/22394
- [x] Gather internal feedback paJDYF-33e-p2
- [x] A document explaining Safe Mode - 2b6c0-pb
- [x] Update stable versions for Jetpack packages. 
- [x] Enhancement from Jetpack: `Jetpack Safe Mode` text when a site is choosing Safe Mode. p9dueE-3Xf-p2#comment-7007 p9dueE-3pz-p2#comment-7155 - https://github.com/Automattic/jetpack/pull/22494

**Comment by htdat** [comment]
Marking blocked based on this comment 
pc2DNy-BV-p2#comment-1319

**Comment by htdat** [comment]
Removed "status: blocked" - ref pc2DNy-BV-p2#comment-1321

**Comment by htdat** [comment]
I've changed the estimate from 3 to 4 as this PR requires a new document explaining Safe Mode too.
