### ISSUE TITLE
E2E enhancements

### ISSUE THREAD

**Issue by jbordonado** [Automattic/woocommerce-payments#5010]
### Problem

Flaky E2E tests are slowing down dev teams and interrupt dev process in case of false alerts.

### Objective

Introduce shortcuts and mocks to improve velocity and stability of E2E tests.
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8032
- [x] https://github.com/Automattic/woocommerce-payments/issues/8031
- [ ] https://github.com/Automattic/woocommerce-payments-meta/issues/83
- [ ] https://github.com/Automattic/woocommerce-payments-meta/issues/82
- [x] https://github.com/Automattic/woocommerce-payments/issues/7495
- [x] https://github.com/Automattic/woocommerce-payments/issues/7286
```

**Comment by vbelolapotkov** [comment]
Added two more tasks to this one based on discussion here: paJDYF-cc7-p2#comment-23044

**Comment by haszari** [comment]
Might need a coordinated program for improving our e2e setup, not clear if this project is aligned with or competing with moving to Playwright (https://github.com/Automattic/woocommerce-payments-meta/issues/330)

**Comment by bborman22** [comment]
Similar to @haszari's question, I put a thumbs down on this one only because I feel like we would get more benefit from the conversion to Playwright. Though I don't think it has to be one or the other, I do think the Playwright conversion should be first priority and some of these additional enhancements _might_ become less urgent.

**Comment by vbelolapotkov** [comment]
Good comments @haszari @bborman22 . 

> not clear if this project is aligned with or competing with moving to Playwright

No, I don't think it's competing with it, and I think they are aligned. Brian made a good point though, it shouldn't be either or, but the scope and focus of each might change depending on which one goes first. And based on the voting results, Playwright migration resonates better with the group.

> I feel like we would get more benefit from the conversion to Playwright.

That's a fair feeling, and thanks for taking it into account while voting.

**Comment by flakas** [comment]
Hi @htdat , I'm reviewing older repo issues, closing what's no longer needed and resurfacing work we still want to do.
Could you please skim through #4795 and #4794 and confirm if we still want to do these?
Looks like we haven't progressed on these in quite a while, so wondering if we still plan to follow up.

Thanks!

**Comment by htdat** [comment]
> Could you please skim through https://github.com/Automattic/woocommerce-payments/issues/4795 and https://github.com/Automattic/woocommerce-payments/issues/4794 and confirm if we still want to do these?

Yes, we still want to do them. However, they're irrelevant to this issue here. We have made a ton of E2E improvements, hence, it's fine to close this issue now.
