### ISSUE TITLE
Currency symbol on cart and checkout is wrong when switching subscription

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#5507]
### Describe the bug

When switching subscription, the currency symbol and decimal format follows the customer currency where it should follow the currency when the subscription was initially purchased.

### To Reproduce

1. Enable switching in subscription settings (wp-admin > WooCommerce > Settings > Subscriptions)

<img width="666" alt="Screenshot 2023-02-02 at 17 20 27" src="https://user-images.githubusercontent.com/73803630/216298261-64664d56-371c-4c65-9a4d-ab2daa0b2990.png">

2. Enable [multi-currency](https://woocommerce.com/document/woocommerce-payments/currencies/multi-currency-setup). Add some currencies, eg `INR` and `JPY`.
3. Create 2 simple subscriptions, one is cheaper than the other.
4. Create a grouped product and add the 2 subscription products under the 'Linked products' option.
5. In USD, purchase the cheaper subscription product.
6. Go to My Accounts > Subscriptions > View the newly purchased subscription.
7. Click on the 'Upgrade or Downgrade' link.
8. Choose the more expensive subscription.
9. Open a new tab and change the customer currency to something else, eg `JPY`.
10. Notice the currency symbol and decimal format (eg `JPY` is a zero-decimal currency and the price is displayed without decimal points) follows the customer currency and not the subscription's currency which is `USD`.

### Actual behavior

The currency symbol and decimal format (eg `JPY` is a zero-decimal currency and the price is displayed without decimal points) follows the customer currency.

### Screenshots

https://user-images.githubusercontent.com/73803630/216297786-a694a853-adb4-4429-820b-0ccfefabe85c.mov

### Expected behavior

The currency symbol and decimal format should follow the subscription's currency which is `USD`.

```[tasklist]
### Tasks
- [x] Replicate the issue.
- [x] Determine why the currency is able to be changed.
- [x] Stop the currency from being able to be changed during a switch or renewal.
- [x] See if tests can be added to make sure this cannot happen again.
```

**Comment by zmaglica** [comment]
Hi @dwainm . Is this issue on Sigma's radar? I am triaging the WCPay backlog, and we're uncertain if you are going to handle it.

**Comment by dwainm** [comment]
Hi @zmaglica, this falls under Sigma. I'll add it to our backlog.

**Comment by tpaksu** [comment]
@shendy-a8c is this the same issue with #5488?

**Comment by dwainm** [comment]
@allie500 I'd prefer we push any MC work to sprint 7 where that will be our focus. So removing you as assigned and pushing this over to that sprint.

**Comment by allie500** [comment]
Sounds good. I was looking at doing some bug squashing last week as it was a short week for me and I didn't want to be holding onto a project issue/PR while AFK that could be holding up the team.

**Comment by jessepearson** [comment]
I ran through the replication steps on this, and there's one thing in the steps I cannot replicate. When opening a new tab for the store, I am not able to see the widget displayed in order to change the currency. Regardless, the currency can still be changed via the URL, which means it's still a problem.

**Comment by jessepearson** [comment]
The issue with why we're seeing this is due to there are checks in the `FrontendCurrencies` class that set the `selected_currency_code` in that class, and those checks happen before the cart itself is loaded from the session. This means the `Compatibility` methods/filters run, however, they are checking the cart for switches or renewals. Since there's nothing in the cart, the selected currency from the widget or url are used.

I've been working on a solution, but it's going to be a little bit of a refactor.

**Comment by jessepearson** [comment]
I finished up the refactor last week and am just working on fixing all of the tests now. Some of the primary checks that were done for the class were changed, so nearly every test needs to be updated, as well. I am also working on making the tests more thorough.
