### ISSUE TITLE
Simplify deposits UI - EPIC - Deposit card (single currency)

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#5686]
### Description

The goal of this project is to give merchants confidence about where there money is, how they get paid, and when their money will be available and deposited into their account.

We will achieve this by implementing an improved design for deposits related information in the payments overview screen (alongside appropriate) documentation.

### Acceptance criteria

- [x] #5694
- [x] **The Deposit card should include**
   - [x] **_Next deposit_** 
       - [x] #5695
       - [x] #5696
       - [x] #5697
   - [x] **_Deposit history_**
       - [x] #5699
       - [x] #5700
   - [x] **Card footer including**
       - [x] https://github.com/Automattic/woocommerce-payments/issues/5719
      
### Designs

**P2:** paJDYF-7fi-p2

<img width="1500" alt="Screenshot 2023-03-08 at 10 54 34 am" src="https://user-images.githubusercontent.com/8490476/223591157-b320b0bd-4869-43fc-8359-50e0cec53844.png">

### Dev notes

> **Note**
> If you're looking at the full set of designs, note that the UX notices ([new merchant hold](https://user-images.githubusercontent.com/8490476/223953723-78aaed81-2a38-4329-8113-a932d4d7f5ea.png), [negative balance](https://user-images.githubusercontent.com/8490476/223953720-c96c62ff-7eef-4c15-9d32-3c4fde9e2782.png), [Capital loan inclusion](https://user-images.githubusercontent.com/8490476/223953712-a67e119b-2450-4f1e-a71f-6bdf0ed75896.png)) will be part of a separate epic. See https://github.com/Automattic/woocommerce-payments/issues/5726.

### Additional context

Project: pdjTHR-2i5-p2

**Comment by james-allan** [comment]
All epic items have been merged and released. Closing this epic.
