### ISSUE TITLE
Epic: WCPay Disputes – Highlight active disputes in Payments → Overview screen

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#6353]
### Description
The goal of this epic is to improve the visibility of active disputes in the payment overview screen, and ultimately make it easier for merchants to respond to disputes.

![payment-overview](https://github.com/Automattic/woocommerce-payments/assets/3147296/986f469e-0a5b-47b9-831b-8b8262569cc4)

![woo-home](https://github.com/Automattic/woocommerce-payments/assets/3147296/35de076e-a660-4832-896f-f438d52bb23c)

### Steps

- [x] #6360
- [x] #6382
- [x] #6370
- [x] #6404
- [x] #6403
- [x] #6485
- [x] #6505
- [x] Tracks event registration
	- [x] #6541
	- Note: Payments → overview disputes task tracking is already setup under the existing `wcadmin_wcpay_overview_task` event, although it has not been registered: https://github.com/Automattic/woocommerce-payments/blob/b39314fbbfa4bf18a21928fc02345a052a07f1bf/client/overview/task-list/dispute-tasks.ts#L33-L35. In #6371 this event name has been corrected to `wcadmin_wcpay_overview_task_click` and will be registered.
- [x] Add testing instructions to this description for impacted flows
	- [x] Active Disputes Overview Task
	- [x] Active Disputes WC Home Task
- [x] Check if there is any impact on critical flows testing instructions – **No impact**
- [x] Update the release testing instructions
- [x] Update WCPay release thread

The above is a high-level summary of the changes in the design. These can be split off as separate issues. Can add / adapt if details change.

### Additional context (internal links)
- Project thread: pdjTHR-2Hv-p2
- Exploration thread: pdjTHR-2F9-p2
- Design i1: paJDYF-8Cm-p2

# Testing flows

## Payments Overview Active Dispute Task

* View the Payments → Overview screen with the following configuration of disputes and confirm it matches the requirements:
	* 0 active disputes (task not visible)
	* 1+ active disputes due more than 7 days in the future (task not visible)
	* 1 active dispute due within 7 days
	* 1 active dispute due within 24h
	* 2+ active disputes of multiple currencies due within 7 days
	* 2+ active disputes of multiple currencies due within 24h
* Check that the task list looks correct with a non-dispute task item enabled alongside the dispute task item.
	* Mark these tasks as visible by returning `true` for `showUpdateDetailsTask` and `wpcomReconnectUrl` in [`WC_Payments_Admin::get_js_settings()`](https://github.com/Automattic/woocommerce-payments/blob/5a3909d4823d3794f53f73fed5d468ca905ca656/includes/admin/class-wc-payments-admin.php#L763-L764).
* Check that the currency amounts match the WC settings after modifying the WC country:
	* Navigate to WooCommerce > Settings > General.
	* Change the Country / State to a region with non-decimal (Japan, Yemen) or three-decimal (Bahrain, Kuwait) display.

### Active dispute task visibility & style requirements

**Single/multiple disputes with > 7 days until due**
* **Visibility**: Not visible

**Single dispute with < 7 days until due**
* **Visibility/colour**: 🟡 `Yellow`
* **Title**: `Respond to a dispute for $123.00`
* **Subtitle**: `By Jun 30, 2023 – 1 week left to respond`
* **Action label**: `Respond now`
* **Action redirect**: Single dispute details page

**Single dispute with < 24 hours until due**
* **Visibility/colour**: 🔴 `Red`
* **Title**: `Respond to a dispute for $123.00 – Last day`
* **Subtitle**: `Respond today by 11:59 PM`
* **Action label**: `Respond now`
* **Action redirect**: Single dispute details page

**Multiple disputes with at least one due within 7 days**
* **Visibility/colour**: 🟡 `Yellow`
* **Title**: `Respond to N active disputes for a total of $123.00, €123.00`
* **Subtitle**: `Last week to respond to N of the disputes`
* **Action label**: `See disputes`
* **Action redirect**: Active disputes list screen

**Multiple disputes with at least one due within 24 hours**
* **Visibility/colour**: 🔴 `Red`
* **Title**: `Respond to N active disputes for a total of $123.00, €123.00`
* **Subtitle**: `Final day to respond to N of the disputes`
* **Action label**: `See disputes`
* **Action redirect**: Active disputes list screen

### Testing Tips

**Creating disputed transactions**

To create a disputed transaction, purchase a product with the Stripe test card `4000000000000259`.

**Mocking dispute due_by when testing**

To mock dispute `due_by` dates testing purposes, add the following logic and adjust the 'days' value: https://github.com/Automattic/woocommerce-payments/blob/56dd736e4b2d335ffcdd4e4a6b676d7df0861c78/client/overview/index.js#L75
```diff
-		activeDisputes,
+		activeDisputes: activeDisputes.map( ( dispute ) => {
+			const days = 6;
+			dispute.due_by = new Date(
+				Date.now() + days * 24 * 60 * 60 * 1000
+			).toISOString();
+			return dispute;
+		} ),
```

## WC Home Active Dispute Task

**Single/multiple disputes with > 7 days until due**
* **Visibility**: Not visible

**Single dispute with < 7 days until due**
* **Title**: `Respond to a dispute for $123.00`
* **Subtitle**: `By Jun 30, 2023 – 1 week left to respond`
* **Action redirect**: Single dispute details page

**Single dispute with < 24 hours until due**
* **Title**: `Respond to a dispute for $123.00 – Last day`
* **Subtitle**: `Respond today by 11:59 PM`
* **Action redirect**: Single dispute details page

**Multiple disputes with at least one due within 7 days**
* **Title**: `Respond to N active disputes for a total of $123.00, €123.00`
* **Subtitle**: `Last week to respond to N of the disputes`
* **Action redirect**: Active disputes list screen

**Multiple disputes with at least one due within 24 hours**
* **Title**: `Respond to N active disputes for a total of $123.00, €123.00`
* **Subtitle**: `Final day to respond to N of the disputes`
* **Action redirect**: Active disputes list screen

#### Testing instructions

<details>
<summary>Mocking disputes</summary>

Unfortunately, testing this organically requires waiting 7+ days after creating a disputed transaction. 

I was able to mock disputes for both **Payments → Overview** and **WC → Home** by insertings the following code to the respective get_* functions and adjusting `due_by` dates as necessary.

https://github.com/Automattic/woocommerce-payments/blob/7a64f278403b087dd2f5716aa5d5ee38d831cff1/includes/core/server/class-request.php#L252

```php
if ( 'wcpay_list_disputes_request' === $hook ) {
	$json     = '
	[
			{
				"wcpay_disputes_cache_id": 398047,
				"stripe_account_id": "acct_1NIiMhCBu6Jj8nBr",
				"dispute_id": "dp_1NKx6XCBu6Jj8nBrO4UXe99M",
				"charge_id": "ch_3NKx6FCBu6Jj8nBr0pPOqaaW",
				"amount": 6000,
				"currency": "gbp",
				"reason": "product_not_received",
				"source": "visa",
				"order_number": 76,
				"customer_name": "Test Shopper",
				"customer_email": "eric.jinks@automattic.com",
				"customer_country": "DE",
				"status": "needs_response",
				"created": "2023-06-20 05:27:49",
				"due_by": "2023-06-29 23:59:59",
				"order": {
					"number": "76",
					"url": "https:\/\/woo-delectably-sparkly-ninja.wpcomstaging.com\/wp-admin\/post.php?post=76&action=edit",
					"customer_url": "admin.php?page=wc-admin&path=\/customers&filter=single_customer&customers=1",
					"subscriptions": []
				}
			},
			{
				"wcpay_disputes_cache_id": 397238,
				"stripe_account_id": "acct_1NIiMhCBu6Jj8nBr",
				"dispute_id": "dp_1NKXStCBu6Jj8nBrs0B9G8uJ",
				"charge_id": "ch_3NKXSZCBu6Jj8nBr1awQDFbd",
				"amount": 12000,
				"currency": "eur",
				"reason": "fraudulent",
				"source": "visa",
				"order_number": 74,
				"customer_name": "Test Shopper",
				"customer_email": "eric.jinks@automattic.com",
				"customer_country": "DE",
				"status": "warning_needs_response",
				"created": "2023-06-19 02:05:11",
				"due_by": "2023-06-28 23:59:59",
				"order": {
					"number": "74",
					"url": "https:\/\/woo-delectably-sparkly-ninja.wpcomstaging.com\/wp-admin\/post.php?post=74&action=edit",
					"customer_url": "admin.php?page=wc-admin&path=\/customers&filter=single_customer&customers=1",
					"subscriptions": []
				}
			},
			{
				"wcpay_disputes_cache_id": 397236,
				"stripe_account_id": "acct_1NIiMhCBu6Jj8nBr",
				"dispute_id": "dp_1NKXQMCBu6Jj8nBrlbISviVo",
				"charge_id": "ch_3NKXQLCBu6Jj8nBr0Ho9gWUZ",
				"amount": 7700,
				"currency": "usd",
				"reason": "product_not_received",
				"source": "visa",
				"order_number": 72,
				"customer_name": "Test Shopper",
				"customer_email": "eric.jinks@automattic.com",
				"customer_country": "DE",
				"status": "needs_response",
				"created": "2023-06-19 02:02:34",
				"due_by": "2023-06-28 23:59:59",
				"order": {
					"number": "72",
					"url": "https:\/\/woo-delectably-sparkly-ninja.wpcomstaging.com\/wp-admin\/post.php?post=72&action=edit",
					"customer_url": "admin.php?page=wc-admin&path=\/customers&filter=single_customer&customers=1",
					"subscriptions": []
				}
			},
			{
				"wcpay_disputes_cache_id": 393773,
				"stripe_account_id": "acct_1NIiMhCBu6Jj8nBr",
				"dispute_id": "dp_1NImELCBu6Jj8nBrENWv168J",
				"charge_id": "ch_3NImEKCBu6Jj8nBr0y3I1qOL",
				"amount": 1400,
				"currency": "usd",
				"reason": "fraudulent",
				"source": "visa",
				"order_number": 70,
				"customer_name": "Test Shopper",
				"customer_email": "eric.jinks@automattic.com",
				"customer_country": "DE",
				"status": "needs_response",
				"created": "2023-06-14 05:26:53",
				"due_by": "2023-06-23 23:59:59",
				"order": {
					"number": "70",
					"url": "https:\/\/woo-delectably-sparkly-ninja.wpcomstaging.com\/wp-admin\/post.php?post=70&action=edit",
					"customer_url": "admin.php?page=wc-admin&path=\/customers&filter=single_customer&customers=1",
					"subscriptions": [
						{
							"number": "71",
							"url": "https:\/\/woo-delectably-sparkly-ninja.wpcomstaging.com\/wp-admin\/post.php?post=71&action=edit"
						}
					]
				}
			},
			{
				"wcpay_disputes_cache_id": 393757,
				"stripe_account_id": "acct_1NIiMhCBu6Jj8nBr",
				"dispute_id": "dp_1NIm41CBu6Jj8nBrN9hCquFx",
				"charge_id": "ch_3NIm40CBu6Jj8nBr1DPP5oNx",
				"amount": 3800,
				"currency": "usd",
				"reason": "fraudulent",
				"source": "visa",
				"order_number": 68,
				"customer_name": "Test Shopper",
				"customer_email": "eric.jinks@automattic.com",
				"customer_country": "DE",
				"status": "needs_response",
				"created": "2023-06-14 05:16:13",
				"due_by": "2023-06-23 23:59:59",
				"order": {
					"number": "68",
					"url": "https:\/\/woo-delectably-sparkly-ninja.wpcomstaging.com\/wp-admin\/post.php?post=68&action=edit",
					"customer_url": "admin.php?page=wc-admin&path=\/customers&filter=single_customer&customers=1",
					"subscriptions": []
				}
			},
			{
				"wcpay_disputes_cache_id": 393755,
				"stripe_account_id": "acct_1NIiMhCBu6Jj8nBr",
				"dispute_id": "dp_1NIm3aCBu6Jj8nBrSuSk19uU",
				"charge_id": "ch_3NIm3ZCBu6Jj8nBr0frWIrse",
				"amount": 6000,
				"currency": "gbp",
				"reason": "fraudulent",
				"source": "visa",
				"order_number": 67,
				"customer_name": "Test Shopper",
				"customer_email": "eric.jinks@automattic.com",
				"customer_country": "DE",
				"status": "needs_response",
				"created": "2023-06-14 05:15:46",
				"due_by": "2023-06-23 23:59:59",
				"order": {
					"number": "67",
					"url": "https:\/\/woo-delectably-sparkly-ninja.wpcomstaging.com\/wp-admin\/post.php?post=67&action=edit",
					"customer_url": "admin.php?page=wc-admin&path=\/customers&filter=single_customer&customers=1",
					"subscriptions": []
				}
			},
			{
				"wcpay_disputes_cache_id": 393725,
				"stripe_account_id": "acct_1NIiMhCBu6Jj8nBr",
				"dispute_id": "dp_1NIihwCBu6Jj8nBrK18xCDFh",
				"charge_id": "ch_3NIihhCBu6Jj8nBr0fMTOywi",
				"amount": 7000,
				"currency": "eur",
				"reason": "fraudulent",
				"source": "visa",
				"order_number": 65,
				"customer_name": "Test Shopper",
				"customer_email": "eric.jinks@automattic.com",
				"customer_country": "DE",
				"status": "needs_response",
				"created": "2023-06-14 01:41:12",
				"due_by": "2023-06-23 23:59:59",
				"order": {
					"number": "65",
					"url": "https:\/\/woo-delectably-sparkly-ninja.wpcomstaging.com\/wp-admin\/post.php?post=65&action=edit",
					"customer_url": "admin.php?page=wc-admin&path=\/customers&filter=single_customer&customers=1",
					"subscriptions": []
				}
			}]
		';
		$data = json_decode( $json, true );
		$data = array_map(
			function( $dispute ) {
				$dispute['due_by'] = '2023-06-21 23:59:59';
				return $dispute;
			},
			$data
		);
		// return just an array of one dispute.
		$data = array_slice( $data, 0, 1 );

		return [
			'data' => $data,
		];
}
```

https://github.com/Automattic/woocommerce-payments/blob/7a64f278403b087dd2f5716aa5d5ee38d831cff1/includes/wc-payment-api/class-wc-payments-api-client.php#L538

```php
$json         = '
[
		{
			"wcpay_disputes_cache_id": 398047,
			"stripe_account_id": "acct_1NIiMhCBu6Jj8nBr",
			"dispute_id": "dp_1NKx6XCBu6Jj8nBrO4UXe99M",
			"charge_id": "ch_3NKx6FCBu6Jj8nBr0pPOqaaW",
			"amount": 6000,
			"currency": "gbp",
			"reason": "product_not_received",
			"source": "visa",
			"order_number": 76,
			"customer_name": "Test Shopper",
			"customer_email": "eric.jinks@automattic.com",
			"customer_country": "DE",
			"status": "needs_response",
			"created": "2023-06-20 05:27:49",
			"due_by": "2023-06-29 23:59:59",
			"order": {
				"number": "76",
				"url": "https:\/\/woo-delectably-sparkly-ninja.wpcomstaging.com\/wp-admin\/post.php?post=76&action=edit",
				"customer_url": "admin.php?page=wc-admin&path=\/customers&filter=single_customer&customers=1",
				"subscriptions": []
			}
		},
		{
			"wcpay_disputes_cache_id": 397238,
			"stripe_account_id": "acct_1NIiMhCBu6Jj8nBr",
			"dispute_id": "dp_1NKXStCBu6Jj8nBrs0B9G8uJ",
			"charge_id": "ch_3NKXSZCBu6Jj8nBr1awQDFbd",
			"amount": 12000,
			"currency": "eur",
			"reason": "fraudulent",
			"source": "visa",
			"order_number": 74,
			"customer_name": "Test Shopper",
			"customer_email": "eric.jinks@automattic.com",
			"customer_country": "DE",
			"status": "warning_needs_response",
			"created": "2023-06-19 02:05:11",
			"due_by": "2023-06-28 23:59:59",
			"order": {
				"number": "74",
				"url": "https:\/\/woo-delectably-sparkly-ninja.wpcomstaging.com\/wp-admin\/post.php?post=74&action=edit",
				"customer_url": "admin.php?page=wc-admin&path=\/customers&filter=single_customer&customers=1",
				"subscriptions": []
			}
		},
		{
			"wcpay_disputes_cache_id": 397236,
			"stripe_account_id": "acct_1NIiMhCBu6Jj8nBr",
			"dispute_id": "dp_1NKXQMCBu6Jj8nBrlbISviVo",
			"charge_id": "ch_3NKXQLCBu6Jj8nBr0Ho9gWUZ",
			"amount": 7700,
			"currency": "usd",
			"reason": "product_not_received",
			"source": "visa",
			"order_number": 72,
			"customer_name": "Test Shopper",
			"customer_email": "eric.jinks@automattic.com",
			"customer_country": "DE",
			"status": "needs_response",
			"created": "2023-06-19 02:02:34",
			"due_by": "2023-06-28 23:59:59",
			"order": {
				"number": "72",
				"url": "https:\/\/woo-delectably-sparkly-ninja.wpcomstaging.com\/wp-admin\/post.php?post=72&action=edit",
				"customer_url": "admin.php?page=wc-admin&path=\/customers&filter=single_customer&customers=1",
				"subscriptions": []
			}
		},
		{
			"wcpay_disputes_cache_id": 393773,
			"stripe_account_id": "acct_1NIiMhCBu6Jj8nBr",
			"dispute_id": "dp_1NImELCBu6Jj8nBrENWv168J",
			"charge_id": "ch_3NImEKCBu6Jj8nBr0y3I1qOL",
			"amount": 1400,
			"currency": "usd",
			"reason": "fraudulent",
			"source": "visa",
			"order_number": 70,
			"customer_name": "Test Shopper",
			"customer_email": "eric.jinks@automattic.com",
			"customer_country": "DE",
			"status": "needs_response",
			"created": "2023-06-14 05:26:53",
			"due_by": "2023-06-23 23:59:59",
			"order": {
				"number": "70",
				"url": "https:\/\/woo-delectably-sparkly-ninja.wpcomstaging.com\/wp-admin\/post.php?post=70&action=edit",
				"customer_url": "admin.php?page=wc-admin&path=\/customers&filter=single_customer&customers=1",
				"subscriptions": [
					{
						"number": "71",
						"url": "https:\/\/woo-delectably-sparkly-ninja.wpcomstaging.com\/wp-admin\/post.php?post=71&action=edit"
					}
				]
			}
		},
		{
			"wcpay_disputes_cache_id": 393757,
			"stripe_account_id": "acct_1NIiMhCBu6Jj8nBr",
			"dispute_id": "dp_1NIm41CBu6Jj8nBrN9hCquFx",
			"charge_id": "ch_3NIm40CBu6Jj8nBr1DPP5oNx",
			"amount": 3800,
			"currency": "usd",
			"reason": "fraudulent",
			"source": "visa",
			"order_number": 68,
			"customer_name": "Test Shopper",
			"customer_email": "eric.jinks@automattic.com",
			"customer_country": "DE",
			"status": "needs_response",
			"created": "2023-06-14 05:16:13",
			"due_by": "2023-06-23 23:59:59",
			"order": {
				"number": "68",
				"url": "https:\/\/woo-delectably-sparkly-ninja.wpcomstaging.com\/wp-admin\/post.php?post=68&action=edit",
				"customer_url": "admin.php?page=wc-admin&path=\/customers&filter=single_customer&customers=1",
				"subscriptions": []
			}
		},
		{
			"wcpay_disputes_cache_id": 393755,
			"stripe_account_id": "acct_1NIiMhCBu6Jj8nBr",
			"dispute_id": "dp_1NIm3aCBu6Jj8nBrSuSk19uU",
			"charge_id": "ch_3NIm3ZCBu6Jj8nBr0frWIrse",
			"amount": 6000,
			"currency": "gbp",
			"reason": "fraudulent",
			"source": "visa",
			"order_number": 67,
			"customer_name": "Test Shopper",
			"customer_email": "eric.jinks@automattic.com",
			"customer_country": "DE",
			"status": "needs_response",
			"created": "2023-06-14 05:15:46",
			"due_by": "2023-06-23 23:59:59",
			"order": {
				"number": "67",
				"url": "https:\/\/woo-delectably-sparkly-ninja.wpcomstaging.com\/wp-admin\/post.php?post=67&action=edit",
				"customer_url": "admin.php?page=wc-admin&path=\/customers&filter=single_customer&customers=1",
				"subscriptions": []
			}
		},
		{
			"wcpay_disputes_cache_id": 393725,
			"stripe_account_id": "acct_1NIiMhCBu6Jj8nBr",
			"dispute_id": "dp_1NIihwCBu6Jj8nBrK18xCDFh",
			"charge_id": "ch_3NIihhCBu6Jj8nBr0fMTOywi",
			"amount": 7000,
			"currency": "eur",
			"reason": "fraudulent",
			"source": "visa",
			"order_number": 65,
			"customer_name": "Test Shopper",
			"customer_email": "eric.jinks@automattic.com",
			"customer_country": "DE",
			"status": "needs_response",
			"created": "2023-06-14 01:41:12",
			"due_by": "2023-06-23 23:59:59",
			"order": {
				"number": "65",
				"url": "https:\/\/woo-delectably-sparkly-ninja.wpcomstaging.com\/wp-admin\/post.php?post=65&action=edit",
				"customer_url": "admin.php?page=wc-admin&path=\/customers&filter=single_customer&customers=1",
				"subscriptions": []
			}
		}]
	';
$data = json_decode( $json, true );
$data = array_map(
	function( $dispute ) {
		$dispute['due_by'] = '2023-06-21 23:59:59';
		return $dispute;
	},
	$data
);
// return just an array of one dispute.
$data = array_slice( $data, 0, 1 );
return [
	'data' => $data,
];
```

</details>

* Tip: To create a disputed transaction, purchase a product with the Stripe test card `4000000000000259`.
* View the WC → Home screen with the following configuration of disputes and confirm it matches the requirements above:
	* 0 active disputes (task not visible)
	* 1+ active disputes due more than 7 days in the future (task not visible)
	* 1 active dispute due within 7 days
	* 1 active dispute due within 24h
	* 2+ active disputes of multiple currencies due within 7 days
	* 2+ active disputes of multiple currencies due within 24h

**Comment by haszari** [comment]
FYI @Jinksi I changed the title back – don't want the epic title to be too specific, this should cover all changes on the overview page.

**Comment by Jinksi** [comment]
No problem @haszari.

Should we move out the WC home dispute task issue to a separate issue/epic, since it is not part of overview page?

"Use same notice wording in WC home "Things to do next" disputes task list item"

**Comment by haszari** [comment]
> Should we move out the WC home dispute task issue to a separate issue/epic, since it is not part of overview page?

I have no objection to that if it fits better elsewhere, but I think it's part of this work – we're updating these notices, and that one is getting updated to be consistent.

Could work equally well in the "maintenance" epic since it's a grab-bag :) 

- https://github.com/Automattic/woocommerce-payments/issues/6356

**Comment by Jinksi** [comment]
> I think it's part of this work

Yeh, I agree and think it is suitable within this epic.
