### ISSUE TITLE
Epic: WCPay Disputes – Highlight active dispute in Woo order details screen

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#6354]
### Description
The goal of this epic is to improve visibility of active disputes in the Woo orders screen, by adding a new notice (and improving clarity of the order note).

<img width="978" alt="Screenshot 2023-05-23 at 1 08 42 PM" src="https://github.com/Automattic/woocommerce-payments/assets/4167300/c5dae493-6736-478d-a2c7-5d1a8ca5f775">

![order-details-screen](https://github.com/Automattic/woocommerce-payments/assets/3147296/770b9d1f-c74c-4388-8670-16e2347a63c5)

⚠️ **Note** – the wording of the notice/note in the screenshot is out of date. Updated wording below.

* Colour and wording:
	* \> 7 days – 🟡 Yellow, `This order has a chargeback dispute of {AMOUNT} labeled as {REASON}. Please respond to this dispute before {DEADLINE}`
	* < 7 days – 🟡 Yellow, `Please resolve the dispute on this order for {AMOUNT} labeled {REASON} by {DEADLINE}. ({N} days left)`
	* < 72hours – 🔴 Red, `Please resolve the dispute on this order for {AMOUNT} labeled {REASON} by {DEADLINE}. ({N} days left)`
	* < 24hours – 🔴 Red, `Please resolve the dispute on this order for {AMOUNT} labeled {REASON} by {DEADLINE}. (Last day today)`

### Steps
- [x] Clearer & more informative order note when order is disputed - see prototype / WIP PRs:
  - https://github.com/woocommerce/woocommerce/pull/38443
  - #6535
  - #6373
- [x] #6379 
- [x] Register Tracks events
	- [x] #6742
- [x] Add testing instructions to this description for impacted flows

The above is a high-level summary of the changes in the design. These can be split off as separate issues. Can add / adapt if details change.

### Additional context (internal links)
- Project thread: pdjTHR-2Hv-p2

## Testing flows

- Install and activate WC 7.9+
- Set up a dispute by purchasing with a [dispute test card](https://stripe.com/docs/testing#disputes).
- View the order edit page and confirm the alert shows correct info and button links to dispute detail. 
- Try various combinations of dispute amount, date, and store settings (e.g. multicurrency) to ensure the notice appears when necessary and renders correctly.
- Ensure the notice is not displayed if the dispute has been lost or otherwise resolved, or the merchant has already submitted evidence (responded).

**Comment by Jinksi** [comment]
I'm un-assigning myself to leave this open for someone to pick up next week.

**Comment by Jinksi** [comment]
Re-opening to handle final tasks in description.

**Comment by Jinksi** [comment]
All tasks complete
