### ISSUE TITLE
Epic: WCPay Disputes-related maintenance

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#6356]
### Description
The goal of this epic to fix any important issues or bugs with disputes that don't neatly fit into the other epics, or require attention across multiple flows. Specifically refining some wording / terms used throughout the user experience.

### Steps
- [x] #6372
- [x] Ensure consistent naming of dispute types across WCPay platform (server, client, documentation)
  - [x] Additional client changes #6611
  - [x] Server: https://github.com/Automattic/woocommerce-payments-server/pull/3436
  - [x] Documentation: pdjTHR-2Hv-p2#comment-3559
  - [x] #6474
     - Including in "this order has been disputed" order note - follow up to #6381 
- [ ] Add testing instructions to this description for impacted flows

Maybe more items added here. Can split off separate issue for each item as they are picked up.

### Additional context (internal links)
- Project thread: tbc

## Testing flows
TBC

**Comment by haszari** [comment]
Note – Stripe refers to these as dispute `reason`s (in API), we sometimes use the term `type`. 

Would be good to confirm which term we want to use going forward.

**Comment by haszari** [comment]
> `fraudulent` (Stripe language) => `transaction unauthorised` to merchants

We may need to review / revise the exact wording of `transaction unauthorised`.

**Comment by haszari** [comment]
## QA / testing instructions for [Clarify "disputed" order note: add amount and deadline PR#6381](https://github.com/Automattic/woocommerce-payments/pull/6381)

1. Purchase a product using a [dispute card number](https://stripe.com/docs/testing#disputes) e.g. `4000000000000259`
  - Note that you can use different [test cards](https://stripe.com/docs/testing#disputes) to generate various kinds of dispute (fraudulent, product not received, etc).
2. View the order edit page for the order: `WooCommerce > Orders`, click order (e.g. most recent order).
3. View order notes in top-right.

<img width="427" alt="Screenshot 2023-05-31 at 1 18 32 PM" src="https://github.com/Automattic/woocommerce-payments/assets/4167300/a7150b57-cb5c-4315-92d6-fab7a7c9a4a4">


Please check the following: 

- There should be an informative order note with correct details of the dispute, for example: `Payment has been disputed for $34.00 with reason product_not_received. Response due by June 7, 2023.`
- Check the details are correct (deadline, reason/type, amount) and consistent with dispute details.
- Click the link in the order note. This should navigate to the correct dispute detail page.

**Comment by Jinksi** [comment]
@brucealdridge @shendy-a8c 

What do you think about removing https://github.com/Automattic/woocommerce-payments/issues/6394 (Payments > Disputes highlight) from this Epic since it was added after our story-pointing?

It can be SP'd as an individual issue – there may be more maintenance issues to include as well.

**Comment by brucealdridge** [comment]
> What do you think about removing ...

@Jinksi 👍 

I'm going to close this issue now as it is now complete.

**Comment by Jinksi** [comment]
Thanks @brucealdridge 🤝

I moved #6394 out of this epic into an individual issue for SP purposes.
