### ISSUE TITLE
Transactions list master issue

### ISSUE THREAD

**Issue by coderkevin** [Automattic/woocommerce-payments#65]
Add necessary JS code to fetch a transaction list into fresh-data state.

- [x] Ensure API calls to hosted site API transaction endpoint works.
- [x] Add fresh-data operation for fetching simple transactions list.
- [x] Ensure pagination works when filtering/sorting/searching has **not** been applied (#225).
- [x] Ensure pagination works when filtering/sorting/searching has been applied (#226).
- [x] Add selectors for transaction list and individual info.
- [ ] Ensure unit testing is adequate.

**Comment by vbelolapotkov** [comment]
Closing since all items were implemented.
