### ISSUE TITLE
Currency symbol and negative indicator ordering need localized?

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#6700]
When I'm using WooCommerce Payments with USD as my store currency, negative amounts (such as the Fees column under Payments > Transactions) are shown as `$-50.00`. 

<img width="364" alt="Screenshot taken on 2023-07-06 at 19 33 10 UTC@2x" src="https://github.com/Automattic/woocommerce-payments/assets/5512652/a3f48d15-4ad3-4e44-a943-43eb8c83c405">

However, in the U.S., the currency symbol is usually after the negative sign, e.g. `-$50.00`.

A straw poll of U.S. a12s in Slack agrees: p1688671462030829-slack-C1Y86QPAQ

Is there some way we can "localize" the display of negative amounts so that it doesn't appear odd for a merchant, depending on their country?
```[tasklist]
### Tasks
- [x] Update CLDR data to v41.3
- [x] Add negativity types to the i18n files for each currency
- [x] Add frontend currency formatter
- [ ] Remove currency negativity sign modification code
```

**Comment by aheckler** [comment]
I should note here that WC Pay isn't even consistent with itself. :( On the order detail page we show negative amounts correctly:

<img width="402" alt="Screenshot taken on 2023-07-06 at 19 48 08 UTC@2x" src="https://github.com/Automattic/woocommerce-payments/assets/5512652/ca0cce86-c98a-472b-b0c7-90cdaf6523fa">

**Comment by zmaglica** [comment]
I think we could parse it based on the currency settings. I will move this issue to the prioritization.

**Comment by htdat** [comment]
This issue is related to `Multi-currency`, so I assume Sigma would work on it (based on team responsibilities Pc2DNy-3z-p2) - cc @dwainm as team lead. Otherwise, let us (team Gamma) know so that we can check which team is most suitable for this task.

**Comment by tpaksu** [comment]
This is because we own the backend currency formatter, but not the frontend currency formatter, which is the `@woocommerce/currency` package. And the tables in the backend screens use that for currency formatting. There needs to be a discussion about what to do. 

The possible solutions: 
- Creating a new currency formatter library with javascript to use on the WCPay side.
- Modifying the existing one, will need a new release.

**Comment by tpaksu** [comment]
Nevermind, I found a way to move the currency sign in front of the currency symbol, but for all currencies, the locale data the script is using needs to be improved. I'll prepare a fix for all currencies.

**Comment by tpaksu** [comment]
### Update:

Increasing the estimate from 1 to 8 because:
- The negativity formats are hard to find in the CLDR package, and it requires extra research.
- Backend JS formatter is ready, but the prices on the frontend are not properly using the `wc_price` filter for all prices, including the code on WC Core, some are implemented like `"-" . wc_price($inversed_negative_amount)` for some reason I don't know yet, like the Refunds and Discounts on the checkout/cart screens. That'll require another PR for the core (and version check to apply the `wc_price` filters).
- The JS is built as an override file for `@woocommerce/currency` package, which doesn't support delivering the negative price format for a currency. 
- There will be another PR to update the WC Core locale info files.
- I need to check every aspect of the plugin to see if I missed re-formatting an negative amount.

**Comment by tpaksu** [comment]
@aheckler I asked ChatGPT if an e-commerce report, such as our transactions page, is a financial document, and it said no:

> An e-commerce website report is not typically considered a financial document in the traditional sense. While an e-commerce website report may contain financial data and metrics related to sales, revenue, and expenses, it is primarily a management or operational document used to analyze and monitor the performance of the e-commerce business.
>
> Financial documents, on the other hand, refer to specific reports and statements that provide a comprehensive overview of the financial position, performance, and cash flows of a company. These documents are typically prepared for external stakeholders, such as investors, lenders, or regulatory authorities, and are governed by accounting standards and regulations.

I think the parentheses only apply for accounting/financial documents, because CLDR data (which I'm using for collecting the specs for each currency) suggests using parentheses for displaying negative currency in accounting context. For the currency specs I compiled, there are three methods of displaying the negative amount: 

- `-`: The usual minus sign before all, is being used in 237 countries (except the below list).
- `o-`: The minus sign coming after the symbol, is being used by 7 countries.
    
    ```
    Central African CFA Franc (Central African Republic)
    Swiss Franc (Switzerland)
    Chilean Peso (Chile)
    US Dollar (Ecuador)
    Danish Krone (Greenland)
    Laotian Kip (Laos)
    Venezuelan Bolívar (Venezuela)
    ```
- `o -`: The minus sign coming after the space between the symbol and the amount, is also being used by 7 countries.

    ```
    Aruban Florin (Aruba)
    Euro (Belgium)
    US Dollar (Bonaire, Sint Eustatius and Saba)
    Euro (Netherlands)
    Norwegian Krone (Norway)
    Norwegian Krone (Svalbard and Jan Mayen)
    Surinamese Dollar (Surinam)
    ```

So, I think the parentheses are not an option for this issue.

**Comment by aheckler** [comment]
> I think the parentheses are not an option for this issue

That's fine by me. 🤷‍♂️ I wouldn't expect negative amounts to be shown in parentheses except, as you say, in accounting documents or maybe spreadsheets. The typical U.S. formatting for a negative amount of currency would be `-$12.34`.

**Comment by tpaksu** [comment]
Added two issues on different repositories that don't handle the negative prices in `wc_price` method, and hardcode in HTML output.

There may be other instances in different repos that do the same thing. I still don't know the exact reason why they are written like that, but I believe there shouldn't be any blockers to move the negative sign to the amount itself.

**Comment by tpaksu** [comment]
Created a PR on WC Core to update the i18n definitions: https://github.com/woocommerce/woocommerce/pull/40101

**Comment by tpaksu** [comment]
Putting this on hold because on WooCommerce repo:
- We need to address all the feedback on https://github.com/woocommerce/woocommerce/pull/40101 to get a final shape to the locale files before merging this, to prevent differences in WC core locale files and WCPay locale files.  
- There seems to be a bug that's affecting the testing of the WC Core PR, it needs to be solved to get the core PR properly tested. An issue is created on https://github.com/woocommerce/woocommerce/issues/40135

**Comment by tpaksu** [comment]
Removed the on-hold status of this PR, and will continue to fix this without the localization efforts, since there are things that needs to be decided in terms of being in sync with Woo Core about the localization sources we share. 

Note for @bborman22: IIUC, the localization files we use from WC Core have no means of testing right now on the WC Core side, and updating it is causing problems as seen in the discussions of woocommerce/woocommerce#40101. We may decide to use the locale files on our side, or agree with them to include those in a shared currency library, which may also create benefit to other plugins. But that requires a deep discussion. And it's only nice to have for now. 

I'll just equalize the rendering of negative amounts on both JS rendered prices and PHP rendered prices, and that I believe will close this issue.
