### ISSUE TITLE
E2E tests for APMs and LPMs

### ISSUE THREAD

**Issue by anu-rock** [Automattic/woocommerce-payments#6727]
The epic to track end-to-end tests for local and additional payment methods such as Apple/Google Pay, iDEAL, Sofort, etc.
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/woocommerce-payments/issues/6725
- [ ] https://github.com/Automattic/woocommerce-payments/issues/6728
- [ ] https://github.com/Automattic/woocommerce-payments/issues/6758
- [ ] https://github.com/Automattic/woocommerce-payments/issues/6759
- [ ] https://github.com/Automattic/woocommerce-payments/issues/6760
- [ ] https://github.com/Automattic/woocommerce-payments/issues/6761
- [ ] https://github.com/Automattic/woocommerce-payments/issues/6762
- [x] https://github.com/Automattic/woocommerce-payments/issues/6763
- [ ] https://github.com/Automattic/woocommerce-payments/issues/6764
- [ ] https://github.com/Automattic/woocommerce-payments/issues/6765
- [ ] https://github.com/Automattic/woocommerce-payments/issues/6767
- [ ] https://github.com/Automattic/woocommerce-payments/issues/6768
```
