### ISSUE TITLE
Epic: Combine Dispute Details into Transaction Details

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#6883]
Project: pdjTHR-2PC-p2

Currently, we have Dispute Details page and Transaction Details page.
We want to combine the two, showing dispute's details on the Transaction Details page.

<img width="1470" alt="dispute_i3" src="https://github.com/Automattic/woocommerce-payments/assets/73803630/731dc70a-36f5-43ac-9e84-fb8078649733">

### TODOs
- [ ] Disputes
  - [x] #6886
  - [x] #6923
  - [x] #6924
  - [x] #6925
  - [x] #6926
  - [x] #6974
  - [x] #6987
  - [x] #7229
  - [x] #6966
  - [x] #6927
  - [x] #7173
  - [ ] #7156. Dropped out of project scope.
- [x] Inquiries
  - [x] #7245
  - [x] #7193
  - [x] #7191
- [ ] Other
  - [x] #7124
  - [x] #6928
  - [x] #6891
  - [x] #6929
  - [ ] Change any link to dispute details link to transaction details link – server. 3750-gh-Automattic/woocommerce-payments-server. Maybe won't fix or moved as maintenance.
- [x] #7289
- [x] #7290
- [x] #7363
- [x] Documentation. https://woocommerce.com/document/woopayments/fraud-and-disputes/managing-disputes/#challenge-or-accept
- [x] [Demo video.](https://github.com/orgs/Automattic/projects/578/views/9?pane=issue&itemId=37782450)

**Comment by haszari** [comment]
Closing! This project is completed.
