### ISSUE TITLE
Transaction Details > Update labels and add fees tooltip when disputed

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#6974]
Part of #6883

Updates to the Transaction Details screen include:

* Update transaction breakdown labels:
	* Refunded → Deducted
	* Fee → Fees
* A click tooltip that only shows if there is a Dispute fee in addition to the transaction fee. Tooltip content includes fee breakdown:
	* Transaction fee
	* Dispute fee
	* Total fee

**Note** the fee breakdown tooltip is planned to include additional fees to be addressed in a future issue outside this project's scope.

![transaction-details-amount-labels-fees](https://github.com/Automattic/woocommerce-payments/assets/3147296/68ca44a8-b7c8-400e-82a1-f21c06f101b6)

With active fees breakdown tooltip:

![image](https://github.com/Automattic/woocommerce-payments/assets/3147296/701f587f-810e-4da8-a3c8-a936647f0827)

**Before**

![image](https://github.com/Automattic/woocommerce-payments/assets/3147296/7f9d260d-2690-40d8-9e54-9f4bde008e64)

### Todo
- [x] Confirm "additional" fees that require the tooltip and are to be listed in the fee breakdown.
	- limiting this issue to `Dispute fee`
- [x] ~Update main currency display to store currency~ Handled in #7124 
- [ ] Create an issue to include additional fees in the fee breakdown tooltip

**Comment by kalessil** [comment]
Hey @Jinksi, is `Base fee` a total of all fees we charged, or do we expect here detailed fee breakdowns?

**Comment by Jinksi** [comment]
Hey @kalessil – I've asked in Slack to confirm what fees we should include here (p1691995379157489-slack-C03LA109BKM). I imagine it would be helpful to include a fee breakdown similar to the one in the timeline.

<img width="791" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/3147296/d1582310-2cfe-4262-9b1e-8f2dca1259cb">

However, the main goal of this issue AFAICT is to help communicate the dispute fee to merchants.

**Comment by souravdebnath1986** [comment]
`Base fee` might be the wrong terminology. The tooltip is referring to `Fee` which is actually the net transaction fee inclusive of base, fx, subs, international card etc. as shown above and is charged as part of transaction processing which is a money movement. 
If there is a fee applied later because of subsequent money movements related to the transaction, for example refunds (we don't currently but hypothetically if we did charge a fee) or disputes, it is called out in the tooltip. cc: @nikkivias

**Comment by kalessil** [comment]
Yep, `Base fee` will be misleading. Could be something like 'Transaction fee'  used in this context?

**Comment by Jinksi** [comment]
I've limited the scope of this issue to show the fee breakdown tooltip only if there is a `Dispute fee` to focus on communicating the dispute fee to merchants.

I'll create an additional issue to explore and include additional fees in the tooltip – outside this project's scope.
