### ISSUE TITLE
Improve handling of 7 day authorization expiration/cancelation

### ISSUE THREAD

**Issue by thenbrent** [Automattic/woocommerce-payments#739]
WC Pay's [first 1* review](https://wordpress.org/support/topic/fatal-error-for-90-of-customers-when-capturing-funds/) is because a merchant attempted to capture charges more than 7 days after they were authorized, but inline with [Stripe's docs](https://stripe.com/docs/payments/capture-later):

> the bank guarantees the amount and holds it on the customer’s card for up to seven days. If the payment is not captured in this time, the payment and authorization are both canceled, and the funds are released.

While the 7 day authorization expiration is mentioned in the [manual capture docs](https://docs.woocommerce.com/document/payments/#section-9) and the tooltip next to the **Manual capture** setting, we can do more to avoid merchants having this experience.

<img width="822" alt="Screen Shot 2020-06-18 at 12 10 38" src="https://user-images.githubusercontent.com/235523/84970489-242a1000-b15e-11ea-84be-7b26df83d933.png">

A few quick wins we can introduce to improve this experience:

1. Display the 7 day expiration in the label on the checkbox instead of hiding it in the tooltip.
1. Change the language to make it clear after 7 days, the authorization can no longer be captured.
1. After enabling the setting, display a confirmation dialogue to have the merchant accept that they are aware they must capture charges within 7 days.
1. Add an order note when the authorization is cancelled.
1. On the **Edit Order** screen, remove the _Capture charge_ action.

@LevinMedia any other ideas?

### Issues

- [x] Display 7-day expiration notice in the manual capture checkbox label #742. Has PR: #747
- [x] Display confirmation dialog when enabling manual capture #743. Has PR: #748
- [x] Update order when authorization has expired #744. Has PR: #757

**Comment by thenbrent** [comment]
Closing this one as #742, #743 & #744 are all closed now. 🎉
