### ISSUE TITLE
Add Tracks tracking

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#74]
**Auth**

- [x] merchant captures an auth

**Transaction**

- [x] - merchant opens transactions list view
- [x] - merchant clicks on a transaction in the list view

**Refund**
- [x] - merchant initiates a refund from edit order

**Deposits**

- [x] - merchant opens deposits list view
- [x] - merchant clicks on a deposit in the list view

**Disputes**
- [x] - merchant opens disputes list view
- [x] - merchant clicks on a dispute in the list view
- [x] - merchant yields on a dispute
- [x] - merchant adds evidence on a dispute
- [x] - merchant submits dispute response

**Sigup**
- [x] - Signup actions on the client side

**Settings**
- [x] View the Settings page
