### ISSUE TITLE
Transactions List View Master Issue

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#82]
paJDYF-6G-p2

Each of the following is easily an issue/PR on its own

- [x] Hook up basic list view (i.e. hardcoded to page 1, max 25) #89 
- [x] Hook up transaction search box
- [x] Hook up download
- [x] Hook up pagination controls
- [x] Hook up summary footer
- [x] Hook up filter component
- [x] Hook up No Transactions view #97
- [x] Handle error when retrieving transactions from API
- [x] Handle missing properties in each transaction in list, so that transactions table page still renders without errors ([#](https://github.com/Automattic/woocommerce-payments/pull/89#discussion_r294000056))
- [ ] Add JS tests: did the component render? did we display known errors correctly? did we display an unknown error correctly? did we display data correctly? is pagination working?

**Comment by vbelolapotkov** [comment]
Closing as done.
