### ISSUE TITLE
Show specific payout error for 'Failed' payouts on payout detail screen

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#8203]
### Describe the bug
Payouts can fail for various reasons: 

- Missing payment details
- Payment to account failed / bounced
- etc (I don't know the full list)

In WooPayments we should surface any error messages or related details of why (e.g. if payout details are missing) 

Here's what a failed payout looks like in the UI (details screen):

<img width="1399" alt="no error message when payout fails" src="https://github.com/Automattic/woocommerce-payments/assets/4167300/636b6d74-8669-45aa-a413-c98108076844">

### To Reproduce
- Visit the Stripe Express dashboard for your test WooPayments account (Payments → Overview → Account Details → Edit Details)
- Update the payout bank account to a [failing test account](https://docs.stripe.com/connect/testing#payouts), e.g. 110000000/000111111116 
- Wait for a scheduled payout to fail

There are likely other testing steps to generate a failed payout. This issue is intended to cover multiple errors/failure modes. 

### Actual behavior
- `Failed` payout shown in UI, with linked transactions, and no error message.

### Expected behavior
- Show an error message or explanation.
- Possibly the linked transactions should be un-linked or greyed out– I'm not sure what this means when the payout failed

```[tasklist]
### Subtasks ( added by @nagpai )
- [x] Capture `failure_code` in our database - https://github.com/Automattic/transact-platform-server/issues/7091
- [x] Expose `failure_code` in service, for failed payout objects that are sent in webhooks -https://github.com/Automattic/transact-platform-server/issues/7092
- [x] Show localized messages related to the `failure_code` on any failed payout
```

**Comment by zmaglica** [comment]
This issue impacts Deposits, so assigning to Helix (based on team responsibilities Pc2DNy-3z-p2) @haszari .
Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by nagpai** [comment]
1. In the Payout Object, Stripe currently shares
   * [failure_code](https://docs.stripe.com/api/payouts/object#payout_object-failure_code)  -  e.g. `invalid_account_number`  . The API docs show an enum of various possible codes. I was however not able to spot `invalid_card` within that, which is frequently visible in our live DB. We may need to get an updated enum + description list from Stripe. 
   * [failure_message](https://docs.stripe.com/api/payouts/object#payout_object-failure_message) - This is a longer human readable message, but available only in English - e.g. - `The bank account details on file are probably incorrect. No bank account could be located with those details.`

2.`failure_code` can be used to have translatable messages on the client with a map. 

3. I have added a note on the other PR - #9878 to check with design if we can include the error message in the header design tweaks we are considering there for the Payout details page.

**Comment by nagpai** [comment]
Added a task-list in the main issue description, and linked two newly created service related issues, that are needed to resolve this issue.

**Comment by rogermattic** [comment]
Thanks for working on this issue!

In the description @haszari shared the example reasons for failed payouts:

>Deposits can fail for various reasons:
- Missing payment details
- Payment to account failed / bounced
- etc (I don't know the full list)



@nagpai  is there any way to know the full list of possible reasons somehow?  Im exploring where would be best to display that warning :)

**Comment by nagpai** [comment]
>@nagpai is there any way to know the full list of possible reasons somehow? Im exploring where would be best to display that warning :)

Hey @rogermattic  - The reasons and the description that will be visible is mentioned in the [Stripe documentation for failure_code ](https://docs.stripe.com/api/payouts/object#payout_object-failure_code). I hope it helps.

**Comment by nagpai** [comment]
Some progress notes: 

1. `failure_code` is now available in Payout objects in API responses. 
2. This can be used to generate localized failure messages on the client side on Payout details page
3. Stripe has a list of `failure_code` s in [their documentation](https://docs.stripe.com/api/payouts/object#payout_object-failure_code).  It may not be updated though, since I see a code of `invalid_card` ( where payout destination is an invalid debit card account ) . This code does not appear in the documentation. 
4. I queried unique failure_message s and tried to find out the failure_code for each from Stripe dashboard event data. I was able to find it for most of them, and have it on an internal Google doc.
