### ISSUE TITLE
Transaction Payment Details View Master Issue

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#83]
paJDYF-7w-p2

Each of the following is possibly an issue/PR on its own:

- [x] Payment Details top level container linked from Transactions (Payment) List View row AND with placeholder children #98 
- [x] Fetch single transaction data for Transaction Details view #228 
- [x] Add Summary child component #202 
- [x] Add Payment child component
- [x] Add Timeline child component #101
- [x] Add Payment child Method component #100
- [x] Add Session child component #99

**Comment by vbelolapotkov** [comment]
Closing as done.
