### ISSUE TITLE
Fix WordPress.Security phpcs reports

### ISSUE THREAD

**Issue by reykjalin** [Automattic/woocommerce-payments#8434]
## Description

This is a follow up to #8415 where there are some issues reported by `phpcs` that were not a straight-forward fix.

Running

```sh
./vendor/bin/phpcs --standard=phpcs.xml.dist $(git ls-files | grep '.php$') --sniffs='WordPress.Security.EscapeOutput,WordPress.Security.ValidatedSanitizedInput'
```

<details><summary>Results in a list of issues in these files (also a command to get just the list of files)</summary>

```sh
./vendor/bin/phpcs --standard=phpcs.xml.dist $(git ls-files | grep '.php$') --sniffs='WordPress.Security.EscapeOutput,WordPress.Security.ValidatedSanitizedInput' | rg 'FILE' | sed 's/FILE: \/path\/to\/wcpay\/repo\/parent\/woocommerce-payments\//* '
```

* `src/Container.php`
* `bin/class-wcpay-changelog-formatter.php`
* `src/Internal/Payment/State/InitialState.php`
* `includes/fraud-prevention/models/class-check.php`
* `src/Internal/DependencyManagement/DelegateContainer/LegacyContainer.php`
* `includes/in-person-payments/class-wc-payments-in-person-payments-receipts-service.php`
* `src/Internal/Payment/State/StateFactory.php`
* `src/Internal/PluginManagement/TranslationsLoader.php`
* `includes/express-checkout/class-wc-payments-express-checkout-button-display-handler.php`
* `src/Internal/DependencyManagement/ExtendedContainer.php`
* `includes/core/server/request/class-list-disputes.php`
* `includes/class-wc-payments-checkout.php`
* `src/Internal/Proxy/LegacyProxy.php`
* `tests/unit/helpers/class-wc-helper-subscription.php`
* `src/Internal/Service/MinimumAmountService.php`
* `src/Internal/Service/OrderService.php`
* `src/Internal/Payment/PaymentRequest.php`
* `includes/core/server/request/class-update-account.php`
* `src/Internal/Payment/State/AbstractPaymentState.php`
* `includes/core/server/class-request.php`
* `includes/class-payment-information.php`
* `includes/core/server/request/class-create-and-confirm-setup-intention.php`
* `includes/multi-currency/MultiCurrency.php`
* `includes/wc-payment-api/class-wc-payments-api-client.php`
* `includes/class-wc-payments-order-service.php`
* `includes/wc-payment-api/class-wc-payments-http.php`
* `includes/class-wc-payments-payment-request-button-handler.php`
* `includes/class-wc-payments-status.php`
* `includes/class-wc-payment-gateway-wcpay.php`
* `includes/class-wc-payments-webhook-processing-service.php`
* `includes/class-wc-payments-account.php`
* `includes/class-wc-payments.php`
* `includes/constants/class-base-constant.php`

</details>

We need to go through all of these issues and either:

1. Fix the issue; or
2. If it's not an issue add an ignore in place.

This is a rule that we should not be adding an ignore for, so it's not feasible to add a project-wide ignore for this.

## Acceptance criteria

No more issues reported by `phpcs`.
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8464
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8465
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8466
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8468
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8469
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8467
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8470
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8471
```

**Comment by zmaglica** [comment]
@jrodger as a ticket triage, I will move this issue to the Other Team queue. I have noticed that this issue is placed on your backlog by CI/CD. If you thunk that this issue doesn't belong where is it now, feel free to apply different focus label or ping me back.

**Comment by vbelolapotkov** [comment]
I'm splitting this issue into multiple smaller once to share the work among teams due to potential security impact.

@reykjalin I'll ask you to do the same with other PHPCS issues created. They are not devops issues, but tech debt issues.

**Comment by vbelolapotkov** [comment]
Closing this one since all the related tasks are closed.
