### ISSUE TITLE
Fix unused parameter phpcs sniffs

### ISSUE THREAD

**Issue by reykjalin** [Automattic/woocommerce-payments#8436]
## Description

This is a follow up to https://github.com/Automattic/woocommerce-payments/pull/8415 where there are some issues reported by phpcs that were not a straight-forward fix.

Running

```sh
./vendor/bin/phpcs --standard=phpcs.xml.dist $(git ls-files | grep '.php$') --sniffs='VariableAnalysis.CodeAnalysis.VariableAnalysis'
```

<details><summary>Results in a list of issues in these files (also a command to get just the list of files)</summary>

```sh
./vendor/bin/phpcs --standard=phpcs.xml.dist $(git ls-files | grep '.php$') --sniffs='VariableAnalysis.CodeAnalysis.VariableAnalysis' | rg 'FILE' | sed 's/FILE: \/path\/to\/wcpay\/repo\/parent\/woocommerce-payments\//* '
```

* `tests/unit/subscriptions/test-class-wc-payments-subscription-service.php`
* `tests/unit/subscriptions/test-class-wc-payments-subscriptions-event-handler.php`
* `includes/payment-methods/class-upe-payment-method.php`
* `tests/unit/subscriptions/test-class-wc-payments-subscriptions-migrator.php`
* `includes/multi-currency/Analytics.php`
* `includes/multi-currency/FrontendCurrencies.php`
* `tests/unit/test-class-compatibility-service.php`
* `src/Internal/Payment/State/AbstractPaymentState.php`
* `tests/unit/multi-currency/test-class-multi-currency.php`
* `tests/unit/test-class-wc-payments-features.php`
* `tests/unit/helpers/class-wc-helper-product-add-ons-helper.php`
* `includes/class-wc-payments-incentives-service.php`
* `tests/unit/test-class-wc-payment-gateway-wcpay-payment-types.php`
* `tests/unit/core/server/request/test-trait-order-info.php`
* `tests/unit/helpers/class-wc-helper-subscriptions-synchroniser.php`
* `tests/unit/multi-currency/compatibility/test-class-woocommerce-subscriptions.php`
* `includes/class-logger.php`
* `includes/multi-currency/MultiCurrency.php`
* `tests/unit/multi-currency/test-class-analytics.php`
* `tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php`
* `includes/wc-payment-api/class-wc-payments-api-client.php`
* `includes/admin/class-wc-payments-admin-sections-overwrite.php`
* `tests/unit/subscriptions/test-class-wc-payments-invoice-service.php`
* `tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-payment-method-order-note.php`
* `tests/unit/subscriptions/test-class-wc-payments-subscription-change-payment-method.php`
* `tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php`
* `tests/unit/test-class-wc-payments-utils.php`
* `tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php`
* `includes/class-wc-payments-webhook-processing-service.php`
* `includes/class-wc-payments.php`
* `includes/class-wc-payments-apple-pay-registration.php`
* `tests/unit/test-class-wc-payment-gateway-wcpay.php`

</details>

These seem to be mostly valid cases. I'd love to see if we can maybe add some rule to `phpcs.xml.dist` that catches these valid cases, e.g. in filters and hooks.

Alternatively we could just ignore these outright. Either way we should go through all of these issues and either:

1. Fix the issue, if it exists;
2. Add ignores in-place via comments; or
3. Add an ignore to `phpcs.xml.dist`.

## Acceptance criteria

No more issues reported by `phpcs`.

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8652
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8653
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8654
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8655
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8656
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8657
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8658
```

**Comment by reykjalin** [comment]
Maybe https://github.com/sirbrillig/phpcs-variable-analysis/ could be a decent fit here to replace this set of rules?

**Comment by vbelolapotkov** [comment]
@reykjalin this one will need to be split into smaller issues. The same as we did for other recent phpcs issues. Could you please take care of it once you have time?

**Comment by reykjalin** [comment]
Yup, once #8556 has been merged we'll have some better tools and direction for managing this across the codebase so I'll split it then 👍

**Comment by reykjalin** [comment]
@vbelolapotkov I've split this up into what I think are correct focuses, but would appreciate a quick review that this is split up correctly 👍
