### ISSUE TITLE
Epic: Show payment activity widget with payment volumes for the period selected by the user (presets)

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#8482]
- All tiles should update when the time selection is changed.
- Clicking on the Time Period filter is recorded as a tracks event - track event name TBD
- Merchant can select a time period from the following presets
  - Today
  - Last 7 days
  - Last 4 weeks
  - Last 3 months
  - Last 12 months
  - Month to date
  - Quarter to date
  - Year to date
  - All time
- Note this epic doesn't include `custom` / calendar input for arbitrary time ranges, that's a separate epic:
  - #8483

### design

![Image](https://github.com/Automattic/woocommerce-payments/assets/4167300/31d7b143-e2a9-462c-ac29-d51f4266ed10)

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8734
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8733
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8735
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8929
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8736
```

**Comment by haszari** [comment]
@shendy-a8c  @jessy-p  do we need to re-estimate this epic because we need to implement the dropdown component, or is the current SP estimate reasonable?

**Comment by haszari** [comment]
FYI – in https://github.com/Automattic/tracks-events-registration/issues/2466 I have work-in-progress event name & props for this:

- Event name: `wcadmin_wcpay_overview_payment_activity_period_change`
- Event props:
  - `start_date` yyyy-mm-dd
  - `end_date` yyyy-mm-dd
  - `preset_name` 

@nagpai can you implement this event in #8910 ? Feel free to iterate on the name & props, and update the registration if needed.

**Comment by nagpai** [comment]
@haszari  - The dropdowns PR is up for review. I will create a separate PR for the click tracking on that.

**Comment by jessy-p** [comment]
Closing this Epic as all the 5 tasks are completed.
