### ISSUE TITLE
Epic: Show a payment activity widget on the overview screen, with total payment volume for the last 7 days, for the store’s primary currency

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#8484]
- This widget appears below the balance box and is independent of currency changes using the currency tab on the balance box.
- This widget always shows payment volume in the store's primary currency.
- On click of the payment volume, redirects to Transactions page filtered by date for all types of Transactions. This click is recorded by track - track event name TBD
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8389
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8595
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8629
- [ ] https://github.com/Automattic/woocommerce-payments-server/issues/5145
- [ ] https://github.com/Automattic/woocommerce-payments-server/issues/5005
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8510
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8511
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8516
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8519
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8593
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8675
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8686
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8708
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8700
```

### Design

See [Figma](https://www.figma.com/file/bIfbBgyBPRzvXEl7dEg3cv/Payment-Widget?type=design&node-id=1502-50978&mode=design&t=yacXI04hBiR8GSPg-0).

![Image](https://github.com/Automattic/woocommerce-payments/assets/3147296/bfd4083f-4235-411a-b7a4-79286d60632a)

**Comment by Jinksi** [comment]
Accidental self-assign ☝️

**Comment by haszari** [comment]
We could split off #8706 to a new epic, since it's new scope. When we planned & estimated this, everyone was assuming that we could link to existing filters on list view.

**Comment by jessy-p** [comment]
Removed #8706  to #8740

**Comment by jessy-p** [comment]
This issue is pending on #8687 (Tracks)

**Comment by haszari** [comment]
Closing, all tasks are done and this is looking good 🎉 

@jessy-p / Helix, please reopen and ping me if this epic (widget + TPV tile in primary currency) still needs work.
