### ISSUE TITLE
Epic: Emoji survey to gather feedback about payments activity widget

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#8485]
### Description

Create an emoji-based survey component to capture the user sentiment for the new Payments Activity Widget (#8484).

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8571
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8314
- [ ] https://github.com/Automattic/woocommerce-payments/pull/8682
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8693
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8724
```

### Acceptance criteria

* Clicking one of the negative options should display a text box where the user can submit additional feedback.
* Submitting a survey should store its response – see project exploration: pdjTHR-3tT-p2#comment-4701
  * Include hidden question with WooPayments version, e.g. 7.5: pdjTHR-3tT-p2#comment-4703
* Optimise for mobile web.
* Tracks event should be recorded for users starting the survey who end up completing OR dismissing/dropping off.

> [!IMPORTANT]  
> Design has been changing iteratively, so keep an eye on the latest changes in Figma.

![Image](https://github.com/Automattic/woocommerce-payments/assets/3147296/6b745cb9-f12b-469a-9b0e-deb9cde32e54)

![Image](https://github.com/Automattic/woocommerce-payments/assets/3147296/cf59f7ad-1a7d-4d48-92b1-2b6d0c9254c7)

### Notes

* See bIfbBgyBPRzvXEl7dEg3cv-fi-1502_50978
* See handed-over PR #8309
* See #8314 for backend handling of survey data

**Comment by Jinksi** [comment]
The handed-over PR #8309 looks like it will 99% cover this issue as-is. I recommend we commandeer it rather than open a new PR.

**Comment by naman03malhotra** [comment]
Hey @Jinksi, I am see two PRs for the Emoji survey:
- https://github.com/Automattic/woocommerce-payments/pull/8309 by Dan
- https://github.com/Automattic/woocommerce-payments/pull/8506 by You
Which one are we continuing with, is there a difference in both?

**Comment by Jinksi** [comment]
I moved Dan's work to #8506 to clean up the mess I made of the commit history in #8309. Commits have been cherry-picked to #8506 and I've continued work on it.

**Comment by Jinksi** [comment]
Re-opening as this epic is not resolved until the sub-tasks are complete

**Comment by Jinksi** [comment]
Decoupling sub-task #8710 which is currently being handled as a follow-up issue.

Closing this epic as complete.
