### ISSUE TITLE
Epic: Explore, document and implement all tracks events needed for payment activity widget project

### ISSUE THREAD

**Issue by jessy-p** [Automattic/woocommerce-payments#8491]
The goal of this issue is to ensure that we have all necessary tracks events in the new or changed UI for payment activity widget.

E.g. consider and add/confirm tracks events for: 

- [x] View payment activity widget, i.e. overview screen
	- `wcadmin_page_view path: payments_overview`  - Woo core, generic event
	- registered here https://github.com/Automattic/tracks-events-registration/blob/40d233ca0d11d069b70bc394a14c93b01c7c74e1/events/wcadmin_page_view.event.json
- [x] Clicks on payment activity widget
  - Clicks on tiles ⇒ list views
	  - `wadmin_wcpay_overview_payment_activity_click`
		  - `source: total_payment_volume`
		  - `source: charges`
		  - `source: refunds`
		  - `source: disputes`
		  - `source: fees` ~~MISSING!~~ 
			  - added in #8921  - though if the tile is not clickable, don't need event ?? TBC
			  - Maybe good to have the event, then we can get data on any clicks 🤔
	- check registered
		- Added registration in https://github.com/Automattic/tracks-events-registration/pull/2467
  - Any other clickable / interactive elements
- [x] List views (transactions, disputes), linked from tiles
   - `wcadmin_page_view path: payments_transactions` for all tiles
      - except `Fees` tile which is not clickable
   - registered https://github.com/Automattic/tracks-events-registration/blob/40d233ca0d11d069b70bc394a14c93b01c7c74e1/events/wcadmin_page_view.event.json
- [x] Changes to view settings for payment activity widget TODO
  - Deposit currency change: [`wcpay_overview_currency_select_change`](https://github.com/Automattic/woocommerce-payments/blob/bf558f8410585ce7db6b062affa504e926883e79/client/components/welcome/currency-select.tsx#L102)
  - Change date range, via presets or custom range (calendar picker) in future. Proposed event and props:
    - Event name: wcadmin_wcpay_overview_payment_activity_period_change
    - Event props:
      - `preset_name` (optional) sent if a preset was selected by merchant, could be key/slug or UI string. This will allow us to observe popularity of different presets.
      - exact dates are sent for all changes
      - `start_date: yyyy-mm-dd` consistent format with other woo events e.g. `wcadmin_orders_edit_status_change`
      - `end date_date: yyyy-mm-dd` 
- [X] Emoji survey
  - Assuming we don't need any tracks events for survey, confirming in comments/internal discussion
  - Click an emoji icon
  - Dismiss or cancel the survey form
  - Submit the survey form

#### questions
- [x] Do we need any tracks events for emoji survey? assuming no
- [x] Do we want any tracks events for tooltips?assuming no
- [x] Fees tile does not link anywhere – is this all good, will merchants be confused, tbc

**Comment by haszari** [comment]
I'm broadening this to cover tracks for the whole project. I suspect most events are in place already but I want to check everything, and it's easier to just check than to search for previous issues/PRs.

**Comment by haszari** [comment]
> Emoji survey TODO Do we need any tracks events for emoji survey?

Checking internally with @souravdebnath1986  if we want any tracks events for emoji survey, assuming no for now since we will have survey responses.  ( p1717985618843579-slack-C06BBFTF6EM )

**Comment by haszari** [comment]
> Do we want any tracks events for tooltips?

@souravdebnath1986  do you want tracks events for the tooltips on each data tile? e.g. count clicks on `Charges` or `Fees` or `Total payment volume` tooltip? (also asked in slack)

<img width="847" alt="Screenshot 2024-06-10 at 2 16 31 PM" src="https://github.com/Automattic/woocommerce-payments/assets/4167300/65a67353-ebdb-4191-96f5-7242e9214898">

**Comment by jessy-p** [comment]
> do you want tracks events for the tooltips on each data tile? e.g. count clicks on Charges or Fees or Total payment volume tooltip? (also asked in slack)

Assuming that we do not need to track the tooltips. @souravdebnath1986

**Comment by jessy-p** [comment]
Closing this issue as there is no pending tracks work required.
