### ISSUE TITLE
Epic: MVP: Pre-launch Tasks for Payment Activity widget

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#8680]
This issue encapsulates the pre-launch tasks for the Payment Activity Widget/Card coming in WooPayments 7.9.

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/tracks-events-registration/issues/2466
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8953
- [ ] https://github.com/Automattic/woocommerce-payments/issues/9011
- [x] Demo pdjTHR-3N2-p2
- [ ] Address feedback from demo
- [ ] Review issues in project backlog that may need resolving prior to launch
- [ ] Ensure public documentation is updated
- [ ] Consider removing test payment activity survey response data that exists in the prod WPCOM database which may pollute data analysis – may be unnecessary since survey responses can be filtered by launch date.
```

#### Survey Test Data removal

Survey for Payment Activity already has some data from testing. See https://github.com/Automattic/woocommerce-payments/pull/8506#issuecomment-2049590016.

As @Jinksi said https://github.com/Automattic/woocommerce-payments/pull/8506#issuecomment-2050697505, we could clean up the DB to get rid of those testing data before launch.

This may be unnecessary since survey responses can be filtered by launch date +

**Comment by frosso** [comment]
Closing - the Payment Activity widget was launched and then entirely removed from the codebase in #10826 (June 2025, commit 320637cb4). This Epic tracks pre-launch prep for a feature that no longer exists, so the remaining checklist items are all moot: the feature flag removal (#8953) is done, and the REST API docs task (#9011) documents a `/reporting/payment_activity` endpoint that's been deleted, so #9011 should likely be closed too. The leftover survey test-data concern is cosmetic and can be filtered by date, as the body itself notes.

If we want to capture _why_ the feature was removed, that belongs in the #10826 discussion rather than here. I think we can close this.
