### ISSUE TITLE
Epic: ensure report (list) views support required filtering needed for Payment Activity widget `View report` links

### ISSUE THREAD

**Issue by jessy-p** [Automattic/woocommerce-payments#8740]
Epic to address the changes to `View Report` links and the linked pages from Payment Activity widget.
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8706
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8705
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8702
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8704
- [ ] https://github.com/Automattic/woocommerce-payments-server/issues/5223
```

**Comment by haszari** [comment]
@jessy-p  @nagpai Does this need design or exploration before we estimate, or do we have enough info to estimate as SP?
