### ISSUE TITLE
[e2e] Migrate multi-currency e2e tests to playwright

### ISSUE THREAD

**Issue by reykjalin** [Automattic/woocommerce-payments#8750]
## Description

In an effort to improve the maintainability of the multi-currency e2e tests we want to migrate them to Playwright. This should offer more reliability when running the tests.

The following tests will have to be migrated:

- `tests/e2e/specs/wcpay/merchant/merchant-admin-multi-currency.spec.js`
- `tests/e2e/specs/wcpay/merchant/merchant-admin-multi-currency-on-boarding.spec.js`
- `tests/e2e/specs/wcpay/merchant/merchant-admin-multi-currency-setup.spec.js`
- `tests/e2e/specs/wcpay/shopper/shopper-checkout-multi-currency.spec.js`

It _may_ be worth it to split this into 2 issues (merchant/shopper) when we start working on this.
```[tasklist]
### Tasks
- [x] `tests/e2e/specs/wcpay/merchant/merchant-admin-multi-currency.spec.js`
- [x] `tests/e2e/specs/wcpay/merchant/merchant-admin-multi-currency-on-boarding.spec.js`
- [x] `tests/e2e/specs/wcpay/merchant/merchant-admin-multi-currency-setup.spec.js`
- [x] `tests/e2e/specs/wcpay/shopper/shopper-checkout-multi-currency.spec.js`
```

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/8750?planning-poker) with Zenhub @asumaran @cesarcosta99 @lovo-h @rafaelzaleski @reykjalin @ricardo

**Comment by rafaelzaleski** [comment]
Shouldn't we create one issue for each test file?

**Comment by reykjalin** [comment]
I think that'd be a good way to split this up 👍

**Comment by bborman22** [comment]
Only reason I hadn't done that is I was thinking the bulk of the changes would be in the utils files, but I'm totally open to whatever approach works best!

**Comment by cesarcosta99** [comment]
@bborman22, as discussed via DM, I'm just dropping a note here to mention that an estimation of 3 was pretty tight for this task given the amount of work and effort required during the PR review and a more accurate estimation would be 4. Since we don't have 4 and 5 would be too much, I won't update this here and the extra effort can be captured later.
