### ISSUE TITLE
Epic: Migrate Stripe PRB to ECE

### ISSUE THREAD

**Issue by bborman22** [Automattic/woocommerce-payments#8768]
The goal of this project is to [migrate](https://docs.stripe.com/elements/express-checkout-element/migration) from Stripe's [PaymentRequestButton](https://docs.stripe.com/stripe-js/elements/payment-request-button) to Stripe's [ExpressCheckoutElement](https://docs.stripe.com/elements/express-checkout-element) for express checkout buttons in WooPayments. 

In doing this migration we aim to increase the number of express payment and wallet options available in WooPayments. We also will aim to address as many existing issues with PRB today as we can using the new tools available with ECE. **The project will be considered complete once all express checkout options are using ECE and we've cleaned up the unused PRB code.**

**Reading Materials**
Early exploration into ECE: pbIwZe-1QB-p2
Description of some of the problems we're facing with PRB: paJDYF-ckK-p2
Early Layout of Phases: https://github.com/Automattic/woocommerce-payments/issues/8501 

Milestones
---

```[tasklist]
### Milestone 1 - Render behind a feature flag and initial test payment in WC Blocks.
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8772
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8773
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8825
```

```[tasklist]
### Milestone 2 - Feature parity with PRBs.
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8867
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8868
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8870
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8869
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8871
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8873
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8874
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8872
- [ ] https://github.com/Automattic/woocommerce-payments/issues/9035
- [ ] https://github.com/Automattic/woocommerce-payments/issues/9067
- [ ] https://github.com/Automattic/woocommerce-payments/issues/9076
```

```[tasklist]
### Milestone 3 - Design.
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8951
- [ ] https://github.com/Automattic/woocommerce-payments/issues/9007
- [ ] https://github.com/Automattic/woocommerce-payments/issues/9005
- [ ] https://github.com/Automattic/woocommerce-payments/issues/9006
- [ ] https://github.com/Automattic/woocommerce-payments/issues/9045
- [ ] https://github.com/Automattic/woocommerce-payments/issues/9066
```

```[tasklist]
### Milestone 4 - Telemetry, security, performance, reliability.
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8948
- [x] Exploratory Testing Session for ECE.
- [ ] https://github.com/Automattic/woocommerce-payments/issues/9049
- [ ] https://github.com/Automattic/woocommerce-payments/issues/9080
```

```[tasklist]
### Milestone 5 - Launch.
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8949
```

```[tasklist]
### Milestone 6 - Post-launch, PRBs removal.
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8950
```

---

```[tasklist]
### Future Work - Phase 2
- [ ] https://github.com/Automattic/woocommerce-payments/issues/9074
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8947
- [ ] https://github.com/Automattic/woocommerce-payments/issues/9034
- [ ] https://github.com/Automattic/woocommerce-payments/issues/9048
- [ ] https://github.com/Automattic/woocommerce-payments/issues/8373
- [ ] https://github.com/Automattic/woocommerce-payments/issues/9026
```

**Comment by frosso** [comment]
Effort is complete
