### ISSUE TITLE
PRBs with Tokenized carts - interesting quirks

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#8841]
### Describe the bug

This is meant to be a collection of weird quirks to resolve before the launch of the tokenized cart feature in the tokenized carts PRBs implementation

```[tasklist]
### Quirks list
- [x] On PDPs, Store API POST requests fail with nonce verification error message ( #8840 )
- [x] Multi-currency isn't supported on Store API requests ( #8816 )
- [x] Order attribution on "Order success" and "Order details" pages is to "Credit card / debit card", instead of "Google Pay (WooPayments)"/"Apple Pay (WooPayments)" ( https://github.com/Automattic/woocommerce-payments/pull/8842 )
- [x] Checkout with UK and CA addresses doesn't work ( #8918 )
- [x] The itemized amount (tax, shipping, etc.) is sometimes not displayed (especially after selecting a different variation on a variable product) ( #8916 )
- [x] Apple Pay shows total as "pending" ( #8916 )
- [x] Testing for subscription products, making sure the subscription renews and the payment method is correctly assigned
- [x] On PDPs, cart is assigned to anonymous customer, rather than the logged-in customer ( https://github.com/Automattic/woocommerce-payments/pull/9021 )
- [ ] PRBs don't support multiple shipping options
```

```[tasklist]
### Store API quirks
- [ ] pay-for-order flow: cannot pay without billing address p1718365667412379-slack-C02TS23QJ1X / https://github.com/woocommerce/woocommerce/issues/48540
```

**Comment by frosso** [comment]
All issues but one have been resolved. The ticket is in a `blocked` status. I'll have a chat with the checkout/Store API team for the implementation of the remaining issue. Some concerns over security came up.
