### ISSUE TITLE
[ECE] Finalize button presentation and design

### ISSUE THREAD

**Issue by reykjalin** [Automattic/woocommerce-payments#9066]
## Description

There are still several issues with the ECE (Stripe's Express Checkout Element) presentation that we need to work through:

```[tasklist]
### Tasks
- [x] https://github.com/Automattic/woocommerce-payments/issues/9006 - Here we need to update the max height across all express payment buttons in WooPayments, including ECE.
- [x] https://github.com/Automattic/woocommerce-payments/issues/9005 - The ECE buttons don't have the correct width in Storefront.
- [x] When WooPay and ECE buttons are rendered on the same page [there's an uneven gap](https://github.com/Automattic/woocommerce-payments/issues/8951#issuecomment-2182004929) between the buttons that [we've been unable to track down](https://github.com/Automattic/woocommerce-payments/issues/8951#issuecomment-2183475932).
- [ ] #8136
```

## Acceptance criteria

* ECE buttons render at least as well as PRB in terms of spacing, design, sizes, responsive breakpoints, etc.
* The tasks listed in the PR description have been completed and/or fixed.

## Testing instructions

See relevant issues and discussions.

**Comment by pierorocca** [comment]
Hey team could we also add this issue @rafaelzaleski has picked up to this list? https://github.com/Automattic/woocommerce-payments/issues/8136 

It would look good on the team in the feature announcement and showcase if this new implementation avoids this very noticeable font size mismatch.

**Comment by haszari** [comment]
What's ECE? Recommend defining the acronym somewhere on these issues for newbies like me :)

AHA! Express Checkout Element https://github.com/Automattic/woocommerce-payments/issues/8768

**Comment by bborman22** [comment]
Closing the epic for ECE design issues that were discovered. Thanks for the great work everyone!
