### ISSUE TITLE
Epic: Saved cards merchant UI

### ISSUE THREAD

**Issue by luizreis** [Automattic/woocommerce-payments#908]
WooCommerce Payments requires that we integrate payment method management into it, due to its purposeful lack of an off-site dashboard.

See paJDYF-Kq-p2 for more details.

**Issues:**
- [ ] Saved cards: View saved payment methods list for a user #909
- [ ] Saved cards: Copy customer ID and card ID on click #910 
- [ ] Saved cards: Add a new payment method with card details #911 
- [ ] Saved cards: Add billing details when saving a payment method #912 
- [ ] Saved cards: Edit a payment method #913 
- [ ] Saved cards: Delete a payment method #914

**Comment by zmaglica** [comment]
Closing for now. More info can be found [here](https://a8c.slack.com/archives/C02L752DS0G/p1643975980351219).
